
var R=[
  {n:"Sea Signora",a:"Via Fiori Chiari 32, Brera",pl:4,pr:"€€€€ · ~120€",cu:"Pesce",tg:"pesce",ws:"https://seasignora.com",st:"Design anni 80, pavimenti in marmo, velluti porpora e acquario cilindrico. Cucina di mare cosmopolita.",mi:{s:0,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:16,l:"16/20"},rv:["Crudi di mare straordinari, materia prima di altissimo livello.","Cucina mediterranea con tocchi mediorientali. Servizio impeccabile.","La frittura di calamari di Mazara con labneh e fantastica."]},
  {n:"Trippa",a:"Via Giorgio Vasari 1, Porta Romana",pl:3,pr:"€€€ · ~50€",cu:"Quinto Quarto",tg:"italiana",ws:"https://trippamilano.it",st:"Diego Rossi reinventa la cucina di recupero con tecnica e passione. Bib Gourmand Michelin.",mi:{s:0,b:1,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["La trippa fritta e un capolavoro: croccante fuori, morbida dentro.","Il vitello tonnato probabilmente il migliore di Milano.","Le tagliatelle al burro: la semplicita come perfezione."]},
  {n:"Seta",a:"Via Andegari 9, Duomo",pl:5,pr:"€€€€€ · ~200€",cu:"Alta Cucina",tg:"italiana",ws:"https://mandarinoriental.com/milan",st:"Due stelle Michelin al Mandarin Oriental. Chef Antonio Guida, cucina italiana nell’olimpo gastronomico.",mi:{s:2,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:19,l:"19/20"},rv:["Una delle esperienze gastronomiche piu complete d’Italia.","Menu degustazione straordinario: tecnica, creativita, tradizione.","Servizio di rara perfezione. Sommelier tra i migliori d’Italia."]},
  {n:"Ratana",a:"Via G. De Castillia 28, Porta Garibaldi",pl:3,pr:"€€€ · ~60€",cu:"Milanese",tg:"italiana",ws:"https://ratana.it",st:"Cucina milanese contemporanea tra gli orti urbani di Porta Garibaldi. Una stella Michelin.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["Il risotto alla milanese e probabilmente il migliore di Milano.","La cotoletta e alta, dorata, burro perfetto.","Il giardino e uno dei piu belli della citta."]},
  {n:"Langosteria",a:"Via Savona 10, Navigli",pl:5,pr:"€€€€€ · ~150€",cu:"Pesce Fine Dining",tg:"pesce",ws:"https://langosteria.com",st:"Il tempio del pesce di lusso dal 2007. Una stella Michelin.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:18,l:"18/20"},rv:["Il plateau di crudi e senza rivali a Milano.","Langoustine, astice, ostriche: qualita costante nel tempo.","Cantina straordinaria: champagne e grandi bianchi italiani."]},
  {n:"Pellico 3",a:"Via Silvio Pellico 3, Duomo",pl:4,pr:"€€€€ · ~100€",cu:"Fine Dining",tg:"italiana",ws:"https://pellico3.it",st:"Fine dining nel centro storico. Eleganza sobria, cucina di alto livello. Una stella Michelin.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["Cucina d’autore senza eccessi, ogni piatto racconta una storia.","Servizio altissimo livello, attento senza essere invadente.","Ottimo per cene d’affari o occasioni speciali."]},
  {n:"Osteria San Giovanni",a:"Via S. Giovanni sul Muro 8, Cairoli",pl:2,pr:"€€ · ~40€",cu:"Lombarda",tg:"italiana",ws:"https://osteriasangiovanni.it",st:"Osteria autentica con cucina della tradizione lombarda. Bib Gourmand.",mi:{s:0,b:1,g:0},gr:{f:2,l:"Due Forchette"},es:{v:13,l:"13/20"},rv:["La cassoeula e leggendaria.","La cotoletta probabilmente la migliore della citta.","Da anni il mio posto preferito per una cena in compagnia."]},
  {n:"Dry Milano",a:"Via Solferino 33, Brera",pl:2,pr:"€€ · ~40€",cu:"Pizza Gourmet",tg:"pizza",ws:"https://drymilano.it",st:"Pioniere della pizza gourmet a Milano. Bib Gourmand.",mi:{s:0,b:1,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["La pizza qui e un’altra cosa rispetto alla media milanese.","La cocktail list e tra le migliori di Milano.","Un’istituzione che ha cambiato la cultura gastronomica milanese."]},
  {n:"Gong",a:"Corso Concordia 8, Porta Venezia",pl:3,pr:"€€€ · ~70€",cu:"Cinese Contemporanea",tg:"asiatica",ws:"https://gongmilano.it",st:"La cucina cinese di lusso a Milano. Design orientale di gran classe.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Il Peking Duck e tra i migliori fuori dalla Cina.","Ambiente di grande fascino, perfetto per ospiti importanti.","Dim sum di qualita superiore rispetto alla media milanese."]},
  {n:"Miyama",a:"Via Bazzini 37, Citta Studi",pl:3,pr:"€€€ · ~70€",cu:"Giapponese",tg:"giapponese",ws:"https://miyamamilan.com",st:"Cucina kaiseki tradizionale. Una stella Michelin.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["Il miglior giapponese tradizionale di Milano senza dubbio.","Sashimi servito con rispetto. Il tonno e straordinario.","Si percepisce subito il rispetto per la tradizione."]},
  {n:"Roppongi",a:"Via Canova 33, Sarpi",pl:3,pr:"€€€ · ~70€",cu:"Sushi Omakase",tg:"giapponese",ws:"https://ristoranteroppongi.it",st:"Omakase e sushi di qualita. Il pesce arriva dal Giappone. Una stella Michelin.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["L’omakase e un’esperienza da vivere almeno una volta.","Toro, uni e salmone selvatico di qualita che non si trova altrove.","Uno dei migliori sushi bar d’Italia."]},
  {n:"Starita",a:"Via Procaccini 20, Sarpi",pl:1,pr:"€ · ~25€",cu:"Pizza Napoletana",tg:"pizza",ws:"https://staritanapoli.it",st:"La leggendaria pizzeria napoletana di Materdei a Milano. Lievito madre e forno a legna.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:13,l:"13/20"},rv:["La pizza napoletana piu autentica di Milano.","Friggitoria straordinaria: montanarine, cuoppo, crocchette.","Prezzi paragonabili a Napoli, qualita idem."]},
  {n:"Bela Tusa",a:"Via Procaccini 37, Sarpi",pl:2,pr:"€€ · ~35€",cu:"Piemontese",tg:"italiana",ws:"https://belatusa.it",st:"Trattoria piemontese autentica. Tajarin, vitello tonnato. Bib Gourmand.",mi:{s:0,b:1,g:0},gr:{f:2,l:"Due Forchette"},es:{v:13,l:"13/20"},rv:["I tajarin al ragu d’anatra sono uno dei piatti piu buoni di Milano.","Il vitello tonnato qui e quello vero: carne tenera, salsa cremosa.","Prezzi contenuti per un’esperienza genuina."]},
  {n:"Trattoria del Nuovo Macello",a:"Via C. Lombroso 20, Porta Romana",pl:2,pr:"€€ · ~40€",cu:"Lombarda",tg:"italiana",ws:"https://trattoriadelnuovomacello.it",st:"Una delle trattorie piu autentiche di Milano. Cucina lombarda vera. Bib Gourmand.",mi:{s:0,b:1,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["La trippa alla milanese e la migliore della citta.","Cassoeula d’inverno: scalda il corpo e l’anima.","Un’istituzione che non ha ceduto alle mode."]},
  {n:"Antica Trattoria della Pesa",a:"Viale Pasubio 10, Moscova",pl:3,pr:"€€€ · ~65€",cu:"Milanese Storica",tg:"italiana",ws:"https://anticatrattoriadellapesa.com",st:"Dal 1880, una delle trattorie piu antiche di Milano. Cucina lombarda classica.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Un pezzo di storia di Milano. Si torna indietro di un secolo.","La cotoletta alla milanese e quella originale. Il riferimento assoluto.","Risotto alla milanese e ossobuco che non deludono mai."]},
  {n:"Trattoria Masuelli San Marco",a:"Viale Umbria 80, Porta Romana",pl:2,pr:"€€ · ~45€",cu:"Lombarda",tg:"italiana",ws:"https://masuelli-trattoria.com",st:"Trattoria familiare dal 1921. Cucina milanese borghese alla quarta generazione. Bib Gourmand.",mi:{s:0,b:1,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["La luganega con pure e il comfort food nella sua forma piu alta.","Gestione familiare alla quarta generazione. Si sente l’orgoglio.","Un’istituzione che resiste al tempo e alle mode."]},
  {n:"Brolo Orto con Cucina",a:"Via E. Oldofredi 2, Porta Garibaldi",pl:3,pr:"€€€ · ~65€",cu:"Vegetariana",tg:"italiana",ws:"https://broloorto.it",st:"L’orto come fonte d’ispirazione. Cucina vegetale d’autore. Michelin Green Star.",mi:{s:0,b:0,g:1},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["La cucina vegetale qui e all’altezza di qualsiasi stellato.","Menu degustazione: viaggio attraverso le stagioni dell’orto.","Giardino interno meraviglioso. D’estate e magico."]},
  {n:"Beef Bar",a:"Piazza Gae Aulenti 5, Porta Nuova",pl:4,pr:"€€€€ · ~90€",cu:"Steakhouse",tg:"internazionale",ws:"https://beefbar.com/en/milan",st:"La celebre steakhouse internazionale a Porta Nuova. Carni pregiate da tutto il mondo.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["La Wagyu A5 si scioglie in bocca. Vale ogni centesimo.","Il Tomahawk per due e uno spettacolo.","Cocktail bar di primissimo livello."]},
  {n:"La Latteria",a:"Via San Marco 24, Brera",pl:2,pr:"€€ · ~35€",cu:"Italiana Classica",tg:"italiana",ws:"https://latteriasanmarco.it",st:"Piccola trattoria storica a Brera. Menu scritto a mano su lavagna. Bib Gourmand.",mi:{s:0,b:1,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["La latteria e un pezzo di Milano che non si dovrebbe mai perdere.","La pasta al pomodoro migliore del 90% dei ristoranti stellati.","L’esperienza vale qualsiasi sacrificio per ottenere un tavolo."]},
  {n:"10 11 Portrait",a:"Corso Venezia 11, Porta Venezia",pl:4,pr:"€€€€ · ~100€",cu:"Fine Dining",tg:"italiana",ws:"https://lungarnocollection.com/portrait-milano",st:"L’hotel Portrait ospita uno dei ristoranti piu glamour di Milano. Cucina italiana d’autore.",mi:{s:0,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:16,l:"16/20"},rv:["Eleganza e sostanza in equilibrio perfetto.","La terrazza sul Corso Venezia e magnifica d’estate.","Carta vini di grande profondita con etichette rare."]},
  {n:"Maoji Street Food",a:"Via Paolo Sarpi 22, Chinatown",pl:1,pr:"€ · ~20€",cu:"Sichuan",tg:"asiatica",ws:"https://maoji.it",st:"Il vero street food del Sichuan in Paolo Sarpi. Piccante, aromatico, autentico.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:11,l:"11/20"},rv:["Il mapo tofu piu autentico fuori dalla Cina.","I noodles freddi al sesamo con pepe di Sichuan sono magnifici.","Prezzi da street food, qualita da ristorante serio."]},
  {n:"Paper Moon Giardino",a:"Via Bagutta 1, San Babila",pl:3,pr:"€€€ · ~75€",cu:"Italiana Classica",tg:"italiana",ws:"https://papermoonmilano.com",st:"Il giardino segreto di Milano. Cucina italiana classica in uno dei cortili piu belli.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Il giardino estivo e tra i luoghi piu belli di tutta Milano.","La cucina italiana classica e eseguita con grande cura.","Servizio impeccabile e discreto."]},
  {n:"Meze",a:"Viale Col di Lana 8, Navigli",pl:2,pr:"€€ · ~35€",cu:"Mediorientale",tg:"internazionale",ws:"https://mezemilano.it",st:"Viaggio culinario nel Medioriente. Meze condivisi, spezie profumate.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:12,l:"12/20"},rv:["I meze sono abbondanti e autentici. L’hummus fatto in casa e un’altra categoria.","Perfetto per gruppi: tutto da condividere, prezzi corretti.","Il baklava fatto in casa e il miglior finale possibile."]},
  {n:"Zio Pesce",a:"Via Conchetta 8, Navigli",pl:2,pr:"€€ · ~45€",cu:"Crudo di Mare",tg:"pesce",ws:"https://ziopesce.it",st:"Piccolo indirizzo ai Navigli dedicato al crudo. Pescato freschissimo.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:13,l:"13/20"},rv:["Il crudo di mare piu fresco di Milano. Ostriche, gamberi, scampi.","Il plateau di crudi e il miglior inizio di serata.","Quasi impossibile trovare posto senza prenotazione."]},
  {n:"Mitu",a:"Via Savona 11, Tortona",pl:2,pr:"€€ · ~40€",cu:"Messicana",tg:"internazionale",ws:"https://mitu.it",st:"La cucina messicana seria che Milano aspettava. Tortillas fatte a mano.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["I tacos al pastor con ananas sono quelli originali.","La carta del mezcal e straordinaria.","Le tortillas fatte a mano fanno tutta la differenza."]},
  {n:"Razdora",a:"Via Molino delle Armi 48, Duomo",pl:3,pr:"€€€ · ~65€",cu:"Emiliana",tg:"italiana",ws:"https://razdora.it",st:"La cucina emiliana nella sua forma piu raffinata. Tortellini in brodo, tagliatelle al ragu.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Il tortellino in brodo originale: piccolo, saporito, brodo profondo.","Le tagliatelle al ragu bolognese sono il piatto cult.","Il culatello e fuori categoria."]},
  {n:"Fioraio Bianchi",a:"Via Montebello 7, Moscova",pl:3,pr:"€€€ · ~60€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://fioraio-bianchi.com",st:"Il ristorante dentro la storica fioreria di Brera. Atmosfera unica tra fiori e luci calde.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Tra i fiori e le luci soffuse si crea vera magia.","Per occasioni speciali e il posto perfetto a Milano.","La carta dei vini e curata con intelligenza."]},
  {n:"Orizzonti",a:"Viale Monte Nero 56, Porta Romana",pl:3,pr:"€€€ · ~60€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://ristoranteorizzonti.it",st:"Cucina italiana contemporanea con forte attenzione agli ingredienti di stagione.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Cucina pulita e precisa, ingredienti di stagione con rispetto.","Carta dei vini sorprendente: etichette ricercate a prezzi onesti.","I primi piatti sono il punto di forza: pasta fatta in casa."]},
  {n:"Da Berti",a:"Via Solari 32, Tortona",pl:2,pr:"€€ · ~38€",cu:"Italiana Tradizionale",tg:"italiana",ws:"https://trattoriadaberti.it",st:"Trattoria milanese classica, vino sfuso, cucina senza mode.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:12,l:"12/20"},rv:["Un’ancora di tradizione nel quartiere Tortona.","Semplicita e qualita in ogni piatto.","L’animella impanata e un capolavoro di cucina di recupero."]},
  {n:"Manna",a:"Via L. Cusani 1, Brera",pl:3,pr:"€€€ · ~55€",cu:"Italiana Creativa",tg:"italiana",ws:"https://ristorantemanna.it",st:"Cucina italiana contemporanea creativa. Ingredienti di stagione e tecniche moderne.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Menu stagionale: ogni visita e una nuova esperienza.","La pasta fresca fatta in casa con farine di qualita eccelsa.","Servizio giovane e preparato, racconta ogni piatto con passione."]},
  {n:"Ba",a:"Via Bagnera 2, Duomo",pl:3,pr:"€€€ · ~60€",cu:"Asiatica Fusion",tg:"asiatica",ws:"https://baresto.it",st:"Viaggio gastronomico attraverso le cucine dell’Asia in uno dei vicoli piu antichi di Milano.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Dim sum di livello autentico: delicati e saporosi.","Atmosfera unica in una delle strade piu antiche della citta.","Cucina fusion che non tradisce le origini asiatiche."]},
  {n:"Cavoli a Merenda",a:"Via Melzo 10, Porta Venezia",pl:2,pr:"€€ · ~40€",cu:"Vegetariana",tg:"italiana",ws:"https://cavoliam.it",st:"Cucina vegetariana creativa che dimostra come si possa mangiare benissimo senza carne.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Finalmente un vegetariano che non sembra un sacrificio.","Anche i carnivori escono soddisfatti.","Ottimo rapporto qualita/prezzo per il quartiere."]},
  {n:"Bottega Lucia",a:"Via P. Castaldi 16, Repubblica",pl:3,pr:"€€€ · ~55€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://bottegalucia.it",st:"Bistrot dal fascino caldo. Cucina italiana gustosa e cocktail bar curato.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:13,l:"13/20"},rv:["Atmosfera bistrot autentica. Il cibo e curato senza fronzoli.","La terrazza estiva e uno dei posti piu piacevoli di Milano.","Il cocktail bar abbina i drink ai piatti con cura."]},
  {n:"Robata Kan",a:"Via Anfossi 10, Porta Romana",pl:3,pr:"€€€ · ~65€",cu:"Robatayaki",tg:"giapponese",ws:"https://robatakan.it",st:"Cottura robatayaki su carbone di qualita: grigliate giapponesi autentiche.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Robata autentico: carbone, temperatura perfetta, prodotti giapponesi.","Yakitori di un livello che non avevo trovato fuori dal Giappone.","Il sake abbinato ai piatti e una scoperta continua."]},
  {n:"Voja",a:"Via Melzo 8, Porta Venezia",pl:2,pr:"€€ · ~40€",cu:"Enoteca con Cucina",tg:"italiana",ws:"https://vojavineria.it",st:"Enoteca con cucina a Porta Venezia. Il vino e protagonista: naturali, biodinamici, rari.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Selezione di vini straordinaria: etichette naturali e biodinamiche.","Il crudo di pesce abbinato al vino giusto e un’esperienza completa.","Uno dei pochi posti dove si beve bene senza spendere una fortuna."]},
  {n:"Kaja Bistrot",a:"Via Vigevano 18, Navigli",pl:2,pr:"€€ · ~45€",cu:"Scandinava",tg:"internazionale",ws:"https://kajabistrot.it",st:"Cucina nordica a Milano: minimalismo, ingredienti d’eccellenza e tecnica scandinava.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Una ventata di freschezza nel panorama milanese. Cucina nordica autentica.","Il salmone marinato in casa con aneto e inaspettatamente eccellente.","La carta dei vini nordici e naturali e una scoperta continua."]},
  {n:"Sali",a:"Via B. Marcello 88, Citta Studi",pl:2,pr:"€€ · ~38€",cu:"Pesce",tg:"pesce",ws:"https://saliristorante.it",st:"Piccolo indirizzo di cucina di mare informale. Menu breve, prodotto freschissimo.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:13,l:"13/20"},rv:["Miglior rapporto qualita/prezzo per il pesce a Milano.","La zuppa di pesce e memorabile: profumata, sostanziosa, generosa.","Un posto che fa della semplicita la propria forza."]},
  {n:"Confine",a:"Piazza XXIV Maggio 8, Navigli",pl:3,pr:"€€€ · ~60€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://confineristorante.it",st:"Sulla Darsena, cucina italiana contemporanea con vista. Ingredienti locali.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["La posizione sulla Darsena e magnifica.","Il risotto alle erbe selvatiche lo ricordero a lungo.","Ottima selezione di vini naturali."]},
  {n:"Casa Tobago",a:"Via Melzo 22, Porta Venezia",pl:2,pr:"€€ · ~45€",cu:"Fusion Caraibica",tg:"internazionale",ws:"https://casatobago.it",st:"Cucina fusion caraibica e latinoamericana. Cocktail tropicali e atmosfera festosa.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:12,l:"12/20"},rv:["I cocktail sono straordinari e originali.","La cucina e una festa di sapori: autenticita e abbondanza.","La ceviche fusion e sorprendentemente ben eseguita."]},
  {n:"Tsukiji Market",a:"Via Mercalli 11, Porta Romana",pl:2,pr:"€€ · ~45€",cu:"Sushi",tg:"giapponese",ws:"https://tsukijimarket.it",st:"Ispirato al mercato del pesce di Tokyo: sushi e sashimi di qualita in ambiente informale.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Qualita del pesce eccezionale per prezzi cosi accessibili.","Sashimi misto: un inno alla freschezza. Tonno sempre perfetto.","Informale e vivace, senza la cerimonia dei giapponesi di lusso."]},
  {n:"Abba",a:"Via Pontaccio 15, Brera",pl:3,pr:"€€€ · ~65€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://abbamilano.it",st:"Cucina italiana contemporanea a Brera. Chef giovane: stagionalita e territorio.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Cucina matura e precisa per uno chef cosi giovane.","Il risotto varia con le stagioni: sempre cremoso e saporito.","Ambiente raffinato senza essere formale."]},
  {n:"Trattoria del Pescatore",a:"Via A. Vannucci 5, Porta Romana",pl:2,pr:"€€ · ~45€",cu:"Pesce Tradizionale",tg:"pesce",ws:"https://trattoriadelpescatoremilano.it",st:"Trattoria di mare classica. Pesce sempre fresco, ricette della tradizione marinara.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:12,l:"12/20"},rv:["Una trattoria di mare come non se ne trovano facilmente.","La frittura mista e il benchmark: leggera, croccante.","Ci si sente ospiti di qualcuno, non clienti."]},
  {n:"Autem",a:"Via Serviliano Lattuada 2, Porta Romana",pl:3,pr:"€€€ · ~70€",cu:"Italiana Creativa",tg:"italiana",ws:"https://autemmilano.com",st:"Cucina italiana reinterpretata con tecnica e creativita. Vini naturali di grande carattere.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Cucina ambiziosa e centrata. Ogni piatto ha una logica chiara.","Il menu degustazione e il modo migliore per vivere Autem.","Una delle migliori esperienze gastronomiche della stagione."]},
  {n:"Sandi",a:"Via Lomellina 14, Porta Romana",pl:2,pr:"€€ · ~42€",cu:"Italiana Moderna",tg:"italiana",ws:"https://sandiristorante.it",st:"Piccolo ristorante di quartiere con cucina sincera. Menu breve e rotazione stagionale.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Un posto che fa bene all’anima. Cucina vera, senza fronzoli.","La pasta fresca e motivo sufficiente per tornare ogni settimana.","Tra i migliori rapporti qualita/prezzo della zona."]},
  {n:"Trattoria Rovello",a:"Via Tivoli 2, Cairoli",pl:2,pr:"€€ · ~40€",cu:"Milanese",tg:"italiana",ws:"https://trattoriarovello.it",st:"Trattoria storica nel centro di Milano. Cucina della tradizione milanese.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Le mondeghili (polpette milanesi) sono quelle vere.","Il risotto al midollo qui lo fanno come una volta.","Una delle trattorie piu autentiche rimaste in centro."]},
  {n:"Eppol Milano",a:"Via Ettore Ponti 35, Navigli",pl:3,pr:"€€€ · ~60€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://eppolmilano.it",st:"Ristorante contemporaneo sui Navigli. Cucina che valorizza il territorio lombardo.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Cucina lombarda reinterpretata con intelligenza.","Carta dei vini tra le migliori dei Navigli.","Servizio professionale e giovane, con vera passione."]},
  {n:"Allangolare",a:"Via B. Marcello 70, Porta Venezia",pl:2,pr:"€€ · ~40€",cu:"Italiana Moderna",tg:"italiana",ws:"https://allangolare.it",st:"Osteria moderna a Porta Venezia. Cucina di stagione legata al territorio.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Il posto di quartiere perfetto: buono, onesto, senza pretese.","La tartare e tra le migliori della zona.","La pasta al ragu bianco non la trovi da nessun’altra parte."]},
  {n:"Terroir",a:"Via Meda 10, Porta Romana",pl:3,pr:"€€€ · ~60€",cu:"Vino Naturale",tg:"italiana",ws:"https://terroirmilano.it",st:"Enoteca con cucina dedicata ai vini naturali. Carta dei vini straordinaria.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Selezione di vini naturali tra le migliori d’Italia.","La cucina e essenziale e corretta, pensata per valorizzare il vino.","Le degustazioni guidate sono eventi preziosi per gli appassionati."]},
  {n:"Via Stampa",a:"Via Vincenzo Monti 30, Cadorna",pl:3,pr:"€€€ · ~70€",cu:"Italiana Fine Dining",tg:"italiana",ws:"https://viastampa.it",st:"Ristorante raffinato a Cadorna. Cucina italiana con forte attenzione ai prodotti regionali.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Ristorante solido e affidabile. Cucina precisa, ingredienti eccellenti.","Cantina eccezionale con etichette rare e sommelier preparato.","Servizio professionale e discreto. Non delude mai."]},
  {n:"Osteria Pugliese Gatto Bianco",a:"Via Jommelli 20, Lambrate",pl:2,pr:"€€ · ~38€",cu:"Pugliese",tg:"italiana",ws:"https://osteriagatobianco.it",st:"La Puglia autentica a Milano: orecchiette, burrata, fave e cicoria.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:12,l:"12/20"},rv:["Le orecchiette alle cime di rapa sono quelle vere.","La burrata fresca arriva direttamente dalla Puglia.","Il pane di Altamura come benvenuto e gia una dichiarazione d’intenti."]},
  {n:"Al Garghet",a:"Via Selvanesco 36, Rozzano",pl:3,pr:"€€€ · ~65€",cu:"Milanese",tg:"italiana",ws:"https://algarghet.it",st:"Trattoria storica in un cascinale lombardo. Cucina milanese autentica con spazio estivo.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Vale il viaggio fuori citta. Cucina milanese vera, non da turista.","D’estate si mangia sotto la pergola con vista sul verde.","Il fagiano in salmi e memorabile."]},
  {n:"Onest",a:"Via Savona 1, Tortona",pl:2,pr:"€€ · ~45€",cu:"Italiana Moderna",tg:"italiana",ws:"https://onestristorante.it",st:"Ristorante contemporaneo nel distretto del design. Cucina di mercato e vini naturali.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Cucina onesta e ben eseguita, come suggerisce il nome.","La pasta del giorno e sempre una piacevole sorpresa.","Miglior rapporto qualita/prezzo nel distretto del design."]},
  {n:"Mater Bistrot",a:"Via Broggi 15, Porta Venezia",pl:2,pr:"€€ · ~40€",cu:"Naturale",tg:"italiana",ws:"https://materbistrot.it",st:"Bistrot dedicato ai prodotti naturali. Cucina vegetale, vini naturali, approccio etico.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Un posto che fa bene e fa del bene. Cucina vegetale di qualita.","La cura per la provenienza degli ingredienti si sente nel gusto.","I dessert sono sorprendentemente buoni e creativi."]},
  {n:"Casazul",a:"Via Vigevano 6, Navigli",pl:2,pr:"€€ · ~40€",cu:"Latinoamericana",tg:"internazionale",ws:"https://casazulmilano.it",st:"Colori e sapori latinoamericani sui Navigli. Cucina fusion con influenze peruviane e messicane.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:12,l:"12/20"},rv:["Il ceviche e fresco e ben bilanciato tra acido e piccante.","Atmosfera festosa e vivace, perfetto per una serata informale.","Le empanadas sono croccanti e ben ripiene."]},
  {n:"Yapa",a:"Via Petrella 12, Porta Venezia",pl:2,pr:"€€ · ~40€",cu:"Peruviana",tg:"internazionale",ws:"https://yaparestaurant.it",st:"Cucina peruviana autentica in ambiente vivace. Ceviche, tiradito, lomo saltado.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Il ceviche e fresco e ben bilanciato. Autenticita garantita.","Il lomo saltado preparato con wok e fuoco vivo.","Cocktail a base di pisco originali e ben costruiti."]},
  {n:"Lubna",a:"Via Argelati 19, Navigli",pl:2,pr:"€€ · ~35€",cu:"Libanese",tg:"internazionale",ws:"https://lubnaristorante.it",st:"La cucina libanese nella sua forma piu autentica. Meze condivisi, pita fresca, hummus.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:12,l:"12/20"},rv:["Il kibbeh e perfetto: croccante fuori, saporito dentro.","L’hummus con burro e pinoli e una rivelazione.","Il fattoush freschissimo. Il miglior libanese della citta."]},
  {n:"Cantina Piemontese",a:"Via Laghetto 2, Duomo",pl:3,pr:"€€€ · ~60€",cu:"Piemontese",tg:"italiana",ws:"https://cantinapiemontese.it",st:"La cucina piemontese nel centro di Milano. Vini delle Langhe, tartufo, fonduta.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Il menu invernale con tartufo bianco d’Alba vale ogni euro.","La bagna cauda e quella autentica.","La cantina con Barolo e Barbaresco e straordinaria."]},
  {n:"Food Writers",a:"Via Vigevano 28, Navigli",pl:2,pr:"€€ · ~40€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://foodwriters.it",st:"Ristorante che racconta il cibo attraverso storie e prodotti selezionati.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Ogni piatto racconta una storia di produttori e territori.","Selezione di formaggi e salumi tra le migliori di Milano.","Un posto che ama il cibo in modo autentico."]},
  {n:"Jiao10",a:"Via Paolo Sarpi 10, Chinatown",pl:1,pr:"€ · ~22€",cu:"Dumplings",tg:"asiatica",ws:"https://jiao10.it",st:"Specialisti dei jiaozi in tutte le forme. Qualita rara a questi prezzi.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:11,l:"11/20"},rv:["I jiaozi al vapore con gamberi e bambu: delicatezza assoluta.","La pasta tirata sottile come si deve.","Prezzi da street food, qualita da ristorante serio."]},
  {n:"Sogni",a:"Via Orti 14, Porta Romana",pl:3,pr:"€€€ · ~60€",cu:"Italiana Creativa",tg:"italiana",ws:"https://sognimilano.it",st:"Piccolo ristorante con cucina italiana creativa. Chef giovane e ambizioso.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Una scoperta bellissima. La cucina e ambiziosa e centrata.","Menu degustazione: viaggio tra creativita e tradizione.","Pochi tavoli garantiscono attenzione personalizzata."]},
  {n:"Mogo",a:"Via Bergamo 6, Porta Venezia",pl:1,pr:"€ · ~18€",cu:"Street Food Fusion",tg:"internazionale",ws:"https://mogomilano.it",st:"Street food fusion con influenze asiatiche e latinoamericane. Veloce, economico.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:11,l:"11/20"},rv:["I bao sono morbidi e ben ripieni.","Qualita degli ingredienti sorprendentemente alta per street food.","Miglior rapporto qualita/prezzo di Porta Venezia."]},
  {n:"Forneria Metropolitana",a:"Via Anfossi 13, Porta Romana",pl:1,pr:"€ · ~20€",cu:"Bakery",tg:"italiana",ws:"https://forneriamet.it",st:"Panificio artigianale con cucina. Pane di qualita eccezionale e panini gourmet.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:12,l:"12/20"},rv:["Il pane e straordinario: crosta, alveolatura, profumo.","I panini sono costruiti con intelligenza e ingredienti di qualita.","La focaccia calda del mattino e un motivo per svegliarsi presto."]},
  {n:"Coke Tales",a:"Via B. Marcello 34, Porta Venezia",pl:2,pr:"€€ · ~35€",cu:"Cocktail Bar",tg:"internazionale",ws:"https://coketales.it",st:"Cocktail bar con cucina fusion. Il cocktail e al centro, la cucina lo accompagna.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:12,l:"12/20"},rv:["Cocktail di livello altissimo. Il bartender crea abbinamenti originali.","La cucina e sorprendentemente buona per un cocktail bar.","Uno dei migliori indirizzi di Porta Venezia per iniziare la serata."]},
  {n:"Iyo",a:"Via Piero della Francesca 74, Municipio 8",pl:4,pr:"€€€€ · ~100€",cu:"Giapponese Contemporanea",tg:"giapponese",ws:"https://iyo.it",st:"Il primo ristorante giapponese in Italia a ottenere una stella Michelin. Cucina nikkei di altissimo livello.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["Una stella Michelin meritatissima. La cucina giapponese raggiunge vette eccezionali.","Il menu omakase e un viaggio tra Giappone e Italia che sorprende ad ogni portata.","Ambiente sofisticato e servizio impeccabile."]},
  {n:"Contraste",a:"Via Meda 2, Porta Romana",pl:5,pr:"€€€€€ · ~180€",cu:"Alta Cucina",tg:"italiana",ws:"https://contrastemilano.it",st:"Una stella Michelin in un palazzo storico. Lo chef Matias Perdomo porta una cucina visionaria che sfida le convenzioni.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:18,l:"18/20"},rv:["Una cucina che sorprende e destabilizza nel senso migliore.","L’ambiente e tra i piu belli di Milano: palazzo storico restaurato con gusto.","Il menu degustazione: ogni portata ha una logica e una tecnica straordinaria."]},
  {n:"Ichikawa",a:"Via Fiori Chiari 1, Brera",pl:4,pr:"€€€€ · ~90€",cu:"Giapponese Sushi",tg:"giapponese",ws:"https://ichikawamilano.it",st:"Sushi bar di riferimento a Brera, pesce di altissima qualita e filosofia tradizionale.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Il pesce e di qualita eccezionale, freschissimo e trattato con rispetto assoluto.","Pochi tavoli, esperienza intima e personalizzata. Prenotazione indispensabile.","Il nigiri di tonno e uno dei migliori fuori dal Giappone."]},
  {n:"La Cantina di Manuela",a:"Via C. Poerio 3, Porta Venezia",pl:2,pr:"€€ · ~40€",cu:"Enoteca con Cucina",tg:"italiana",ws:"https://lacantinadimanuela.it",st:"Enoteca con cucina a Porta Venezia. Selezione di vini di piccoli produttori, taglieri curati.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:13,l:"13/20"},rv:["Una delle migliori selezioni di vini naturali e artigianali di Milano.","I taglieri con salumi e formaggi selezionati sono il modo perfetto per iniziare la serata.","Ambiente accogliente e informale, perfetto per una cena in compagnia."]},
  {n:"Osaka",a:"Via Valenza 18, Navigli",pl:2,pr:"€€ · ~40€",cu:"Giapponese",tg:"giapponese",ws:"https://osakaristorante.it",st:"Storico ristorante giapponese dei Navigli. Cucina autentica e prezzi onesti.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Un classico dei Navigli che non tradisce mai. Cucina giapponese autentica.","Il ramen e il sushi sono preparati con cura e ingredienti freschi.","Ambiente informale e accogliente."]},
  {n:"Sushi Matsu Omakase",a:"Via Napo Torriani 34, Repubblica",pl:4,pr:"€€€€ · ~120€",cu:"Sushi Omakase",tg:"giapponese",ws:"https://sushimatsu.it",st:"Omakase puro. Il pesce arriva dal Giappone e il cuoco lavora davanti agli ospiti con precisione.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["L’omakase qui e un’esperienza autentica e commovente.","Il pesce importato dal Giappone e di una qualita rara in Italia.","Pochi posti al bancone, prenotazione con mesi di anticipo."]},
  {n:"Le Nove Scodelle",a:"Via Casale 5, Porta Venezia",pl:2,pr:"€€ · ~35€",cu:"Cinese Regionale",tg:"asiatica",ws:"https://lenovescodelle.it",st:"Cucina cinese regionale autentica. Piatti dello Yunnan e del Sichuan con ingredienti importati.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["La cucina cinese piu autentica di Milano. Sapori profondi e ingredienti rari.","I noodles dello Yunnan fatti a mano sono un piatto memorabile.","Un posto che ha cambiato la percezione della cucina cinese a Milano."]},
  {n:"Azabu 10",a:"Via San Glicerio 6, Bicocca",pl:4,pr:"€€€€ · ~120€",cu:"Sushi Omakase",tg:"giapponese",ws:"https://azabu10byarcieri.com",st:"Chef Andrea Arcieri porta a Milano un omakase di 22-25 portate tra pesce frollato e tecnica edomae. Premio Novita Gambero Rosso Sushi 2025.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Un talento quasi geniale. Il pesce frollato e un altra dimensione del sushi.","Tonno ikejime e abbinamenti arditi ma centratissimi.","Il banco da 10 posti e un rito: ogni portata e un piccolo capolavoro."]},
  {n:"Nobu Milano",a:"Via Gastone Pisoni 1, Duomo",pl:5,pr:"€€€€€ · ~150€",cu:"Giapponese Fusion",tg:"giapponese",ws:"https://noburestaurants.com/milan",st:"L unica sede italiana della leggendaria catena di Nobu Matsuhisa, dentro l Armani Hotel. Cucina giapponese con influenze peruviane.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Il black cod miso e il piatto iconico: leggendario e irripetibile.","Ambiente fashion e internazionale al massimo.","Il lounge bar e uno dei posti piu glamour della citta."]},
  {n:"El Porteno",a:"Via G. Galeazzo 25, Ticinese",pl:3,pr:"€€€ · ~60€",cu:"Argentina",tg:"internazionale",ws:"https://www.elporteno.it",st:"Il tempio dell asado argentino a Milano dal 2000. Carni eccellenti, atmosfera autentica. Tre sedi in citta.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:13,l:"13/20"},rv:["Il bife de lomo argentino e tenero e saporito come a Buenos Aires.","L asado cotto su brace viva: tecnica e rispetto per la materia prima.","Atmosfera calda e conviviale, perfetta per cene in gruppo."]},
  {n:"El Carnicero",a:"Via Spartaco 31, Porta Romana",pl:3,pr:"€€€ · ~65€",cu:"Steakhouse Argentina",tg:"internazionale",ws:"https://www.elcarnicero.com",st:"Dal 2013 il riferimento milanese per la carne di qualita. Tre sedi in citta, carni da tutto il mondo alla griglia.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:13,l:"13/20"},rv:["La Entrana argentina e succosa e perfettamente cotta sulla brace.","La provoleta e gia un capolavoro.","Il Tomahawk di Black Angus australiano vale ogni euro."]},
  {n:"Denis Pizza di Montagna",a:"Via Statuto 16, Moscova",pl:2,pr:"€€ · ~35€",cu:"Pizza di Montagna",tg:"pizza",ws:"https://denispizza.it",st:"Denis Lovatel porta a Milano la sua pizza di montagna: impasto croccante e leggero, ingredienti alpini. 50 Top Pizza.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Una pizza che racconta le Dolomiti ad ogni morso. Croccante, leggera, memorabile.","Gli ingredienti di montagna sono di qualita rara.","Uno dei locali piu belli di Moscova."]},
  {n:"Terrazza Triennale",a:"Viale Alemagna 6, Parco Sempione",pl:3,pr:"€€€ · ~65€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://terrazzatriennale.it",st:"Rooftop del Palazzo dell Arte con vista mozzafiato su Milano. Menu stagionale di Tommaso Arrigoni. Vista Castello e Madonnina.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["La vista sullo skyline di Milano dalla terrazza non ha rivali in citta.","Il menu Meneghinas con tapas lombarde e cocktail vintage e brillante.","D estate sotto il cielo con Castello e Duomo all orizzonte e magico."]},
  {n:"Horto",a:"Via San Protaso 5, Cordusio",pl:5,pr:"€€€€€ · ~185€",cu:"Alta Cucina Sostenibile",tg:"italiana",ws:"https://hortorestaurant.com",st:"Una stella Michelin e Green Star sul rooftop di The Medelan. Norbert Niederkofler: fornitori entro un ora da Milano, stagionalita assoluta.",mi:{s:1,b:0,g:1},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["La tartare di anguria con caviale di storione e straordinaria.","Il risotto alle fragole fermentate e memorabile. La terrazza con Madonnina e unica.","Cucina etica che non sacrifica il gusto. Uno dei migliori di Milano."]},
  {n:"Zero Milano",a:"Corso Magenta 87, Cadorna",pl:3,pr:"€€€ · ~55€",cu:"Giapponese",tg:"giapponese",ws:"https://zero-milano.it",st:"Dal 2006 nella guida Michelin. Chef Hide Shinohara: tradizione giapponese e creativita italiana in perfetto equilibrio.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["I carpacci 007 con salsa calda sono il piatto firma: straordinari.","Zero compromessi sulla qualita: materie prime eccezionali.","Tra i migliori sushi di Milano da anni."]},
  {n:"Casa Camperio",a:"Via Giuliani 6, Duomo",pl:3,pr:"€€€ · ~60€",cu:"Italiana Fusion",tg:"italiana",ws:"https://casacamperio.com",st:"Michelin Plate 2025. Cucina italiana con tocchi giapponesi, cucina a vista, giardino. Chef Roberto Conti (ex Trussardi alla Scala).",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Il risotto alla milanese accanto al maki roll: fusione che funziona.","Servizio di rara gentilezza. Uno degli spazi piu eleganti del centro.","Il cocktail bar abbina drink e piatti con intelligenza."]},
  {n:"Risus Risotteria",a:"Via Panfilo Castaldi 20, Porta Venezia",pl:2,pr:"€€ · ~30€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://risus.family",st:"La risotteria contemporanea di Milano: menu completamente gluten free con risotti classici e gourmet.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:12,l:"12/20"},rv:["Il risotto milanese con ossobuco e eseguito con tecnica e cura.","Le Bombas de Riso sono il piatto da ordinare assolutamente.","Ottimo rapporto qualita/prezzo per la zona Buenos Aires."]},
  {n:"Murataya",a:"Via San Glicerio 2, Bicocca",pl:2,pr:"€€ · ~45€",cu:"Giapponese Tradizionale",tg:"giapponese",ws:"https://www.muratayatrattoriagiapponese.com",st:"Trattoria giapponese autentica a conduzione familiare dello chef Hitoshi Murata. Cucina casalinga nipponica, nessun sushi all-you-can-eat.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Cucina giapponese vera, non fusion: sapori autentici e materie prime eccellenti.","Lo chef Murata ti fa sentire ospite della sua casa di Tokyo.","La tempura soba e i piatti del giorno sono sempre una scoperta."]},
  {n:"Anima",a:"Via Carlo de Cristoforis 6, Porta Garibaldi",pl:4,pr:"€€€€ · ~140€",cu:"Alta Cucina Creativa",tg:"italiana",ws:"https://www.enricobartolini.net",st:"Una stella Michelin firmata Enrico Bartolini nel Milano Verticale. Chef resident Michele Cobuzzi porta la Puglia a Milano con tecnica e creativita.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["Cucina pugliese elevata all alta gastronomia: storia personale nel piatto.","I Bottoni di gallina nostrana con cime di rapa sono tra i piatti piu riusciti della citta.","Sommelier e sala tra i migliori di Milano."]},
  {n:"Bauscia",a:"Via dell Orso 2, Brera",pl:3,pr:"€€€ · ~65€",cu:"Milanese Contemporanea",tg:"italiana",ws:"https://bausciamilano.com",st:"Cucina milanese rivisitata nel cuore di Brera. Splendido giardino interno. Risotto alla milanese con midollo, cotoletta.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:13,l:"13/20"},rv:["Il risotto alla milanese mantecato con midollo: zafferano intenso e cremoso.","La cotoletta con salsa agrumata e il secondo piatto di riferimento.","Il giardino interno fiorito d estate e tra i posti piu belli di Brera."]},
  {n:"Trattoria Don Ciccio",a:"Via Losanna 11, Isola",pl:2,pr:"€€ · ~38€",cu:"Siciliana",tg:"italiana",ws:"https://www.doncicciomilano.it",st:"Vera cucina siciliana da quattro generazioni, originari di Bagheria. Trattoria autentica nel quartiere Isola.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:12,l:"12/20"},rv:["La pasta con le sarde e quella autentica: uvetta, pinoli, finocchietto.","La caponata fatta in casa e complessa e profumata come quella di Bagheria.","Una trattoria familiare che conserva una tradizione preziosa."]},
  {n:"Nott",a:"Piazza del Duomo, Duomo",pl:3,pr:"€€€ · ~65€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://nottmilano.it",st:"Ristorante contemporaneo nel cuore di Milano. Cucina italiana moderna con forte attenzione alla stagionalita.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Cucina pulita e precisa, ingredienti di stagione ben valorizzati.","Uno dei nuovi indirizzi piu interessanti del centro citta.","Un alternativa solida ai grandi stellati."]},
  {n:"Inno",a:"Piazza Duomo ang. Via G. Mazzini 2, Duomo",pl:4,pr:"€€€€ · ~100€",cu:"Fusion Messico-Giappone",tg:"internazionale",ws:"https://innomilano.it",st:"Aperto aprile 2026. Al secondo piano con vista spettacolare sul Duomo. Chef Marcos Cardoso fonde cucina messicana e giapponese.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["La vista sul Duomo dalla terrazza e probabilmente la migliore di Milano.","Pollo in tempura con gelato al mango: abbinamento audace che sorprende.","Design raffinato. Milano internazionale al massimo."]},
  {n:"Gio Gio s",a:"Via Caminadella 7, Duomo",pl:3,pr:"€€€ · ~60€",cu:"Mediterranea Cosmopolita",tg:"internazionale",ws:"https://giogioscafe.com",st:"Aperto aprile 2026. Chef Raphael Duntoye (Londra, Dubai). Cucina mediterranea contemporanea per la condivisione. Giardino urbano.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["La tartare di tonno con agrumi e gia un piatto cult della nuova Milano.","Spazio unico: giardino urbano con velluti e piante botaniche.","Il Mediterraneo con occhio cosmopolita."]},
  {n:"Creda",a:"Via Orti 12, Porta Romana",pl:2,pr:"€€ · ~30€",cu:"Campana",tg:"italiana",ws:"https://creda.eatbu.com",st:"Gastronomia popolare: cucina partenopea autentica dalla colazione alla cena. Banco asporto e sala ristorante.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:12,l:"12/20"},rv:["Cucina napoletana vera a Milano: sapori di casa, nessuna concessione alla moda.","Il bancone gastronomia e un ancora di qualita in zona Porta Romana.","Dalla colazione al dopocena: formato versatile e genuino."]},
  {n:"Futura Pizzeria Romana",a:"Via Pietro Borsieri 28, Isola",pl:2,pr:"€€ · ~30€",cu:"Pizza Romana",tg:"pizza",ws:"https://futurapizzeria.com",st:"La pizza tonda romana di Luca Pezzetta nel quartiere Isola. Sottile, leggera, bordo bruciato. 50 Top Pizza.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["La tonda romana piu autentica di Milano: sottile, croccante, bordo bruciacchiato.","Luca Pezzetta e il miglior pizzaiolo romano arrivato a Milano.","Diventata subito un culto: prenotazione sempre difficilissima."]},
  {n:"Bice Restaurant",a:"Via Borgospesso 12, San Babila",pl:4,pr:"€€€€ · ~90€",cu:"Italiana Classica",tg:"italiana",ws:"https://www.bicemilano.it",st:"Storico ristorante milanese fondato nel 1926 in zona San Babila. Cucina italiana tradizionale in ambiente elegante.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Un istituzione di Milano dal 1926: la cucina italiana nell accezione piu nobile.","Ambiente elegante, discreto e senza tempo. Perfetto per cene importanti.","La tradizione rispettata senza eccessi."]},
  {n:"Yajiri Maison by Yumi",a:"Via Gorani 3, Duomo",pl:3,pr:"€€€ · ~70€",cu:"Giapponese Contemporanea",tg:"giapponese",ws:"https://yajirimilano.com",st:"Ristorante giapponese nel cuore di Milano con approccio creativo e materie prime di eccellenza.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Una delle proposte giapponesi piu interessanti degli ultimi anni a Milano.","Equilibrio perfetto tra tradizione e tocchi contemporanei.","Ambiente raccolto e intimo, servizio attento e appassionato."]},
  {n:"Zelo",a:"Via Villoresi 16, Navigli",pl:3,pr:"€€€ · ~60€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://zelomilano.it",st:"Cucina italiana contemporanea sui Navigli. Ambiente curato, ingredienti di stagione, carta dei vini interessante.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Cucina precisa e ben centrata, con prodotti di qualita.","Ambiente piacevole, perfetto per una cena rilassata sui Navigli.","La carta dei vini offre etichette ricercate a prezzi onesti."]},
  {n:"Particolare",a:"Via Sottocorno 13, Porta Venezia",pl:3,pr:"€€€ · ~65€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://particolaremilano.it",st:"Ristorante contemporaneo a Porta Venezia. Cucina italiana di qualita in ambiente elegante e raccolto.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Un posto davvero particolare: cucina curata e atmosfera intima.","I primi piatti sono il punto di forza, sempre eseguiti con precisione.","Servizio attento e discreto, perfetto per occasioni speciali."]},
  {n:"Inno",a:"Piazza Duomo ang. Via G. Mazzini 2, Duomo",pl:4,pr:"€€€€ · ~100€",cu:"Fusion Messico-Giappone",tg:"internazionale",ws:"https://innomilano.it",st:"Aperto aprile 2026. Al secondo piano con vista spettacolare sul Duomo. Chef Marcos Cardoso fonde cucina messicana e giapponese.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["La vista sul Duomo dalla terrazza e probabilmente la migliore di Milano.","Pollo in tempura con gelato al mango: abbinamento audace che sorprende.","Design raffinato. Milano internazionale al massimo."]},
  {n:"Trattoria da Panciroli",a:"Via Vigevano 6, Navigli",pl:2,pr:"€€ · ~35€",cu:"Italiana Tradizionale",tg:"italiana",ws:"https://trattoriadapanciroli.it",st:"Storica trattoria milanese ai Navigli. Cucina della tradizione genuina, ambiente informale, prezzi onesti.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:12,l:"12/20"},rv:["Una trattoria vera, senza fronzoli: cucina casalinga di grande qualita.","I Navigli che non ti aspetti: niente turisti, solo milanesi doc.","Il risotto e i secondi della tradizione sono il motivo per tornare."]},
  {n:"Trattoria della Gloria",a:"Via Gustavo Fara 14, Repubblica",pl:2,pr:"€€ · ~38€",cu:"Italiana Tradizionale",tg:"italiana",ws:"https://trattoriadellagloria.it",st:"Trattoria classica milanese in zona Repubblica. Cucina della tradizione lombarda con materie prime selezionate.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["La cucina lombarda nella sua forma piu onesta e diretta.","Il cotechino con lenticchie e un piatto da non perdere.","Gestione familiare che mette a proprio agio dal primo momento."]},
  {n:"Hazama",a:"Via Disciplini 5, Duomo",pl:4,pr:"€€€€ · ~100€",cu:"Giapponese Omakase",tg:"giapponese",ws:"https://hazamamilan.com",st:"Omakase giapponese di alta precisione nel centro di Milano. Pesce freschissimo, tecnica edomae, esperienza intima al bancone.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Un omakase di grande livello: pesce eccellente e tecnica impeccabile.","Atmosfera raccolta e serena, ogni portata e una piccola opera.","Tra i migliori indirizzi giapponesi di nuova generazione a Milano."]},
  {n:"Emoraya",a:"Via Vigevano 20, Navigli",pl:2,pr:"€€ · ~40€",cu:"Thai",tg:"asiatica",ws:"https://emoraya.it",st:"Cucina thai autentica ai Navigli. Sapori intensi, erbe fresche, ricette tradizionali eseguite con materie prime di qualita.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Il miglior thai di Milano: sapori autentici e spezie bilanciate.","Il pad thai e il curry verde sono i piatti di riferimento.","Ambiente informale e vivace, perfetto per una serata ai Navigli."]},
  {n:"Brolo",a:"Via Palermo 13, Brera",pl:3,pr:"€€€ · ~60€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://broloorto.it",st:"Cucina italiana contemporanea ispirata all orto e alla stagionalita. Ingredienti di piccoli produttori, ambiente caldo e accogliente.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Cucina che rispetta la stagionalita con risultati sempre convincenti.","I vegetali sono protagonisti assoluti, trattati con grande rispetto.","Un posto genuino e piacevole, lontano dalle mode."]},
  {n:"Rame Bistrot",a:"Via Poerio 3, Porta Venezia",pl:2,pr:"€€ · ~42€",cu:"Italiana Moderna",tg:"italiana",ws:"https://ramebistrot.it",st:"Bistrot contemporaneo a Porta Venezia. Cucina italiana moderna, ingredienti selezionati, atmosfera calda e informale.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Un bistrot solido e affidabile: cucina curata senza fronzoli.","I primi piatti fatti in casa sono il punto di forza del menu.","Servizio gentile e ambiente piacevole, perfetto per una cena di quartiere."]}
  ,{n:"Dee Thai",a:"Via Amerigo Vespucci 12, Porta Nuova",pl:2,pr:"€€ · ~35€",cu:"Thai Autentica",tg:"asiatica",ws:"https://www.google.com/search?q=Dee+Thai+Milano",st:"Cucina thai autentica a Porta Nuova. Sapori decisi, ingredienti freschi, atmosfera vivace.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:12,l:"12/20"},rv:["Curry autentici e ben bilanciati.","Street food thai in versione milanese.","Ottimo rapporto qualita/prezzo."]}
  ,{n:"Yajiri Maison",a:"Via Carlo Goldoni 36, Porta Venezia",pl:3,pr:"€€€ · ~55€",cu:"Izakaya Contemporanea",tg:"giapponese",ws:"https://www.google.com/search?q=Yajiri+Maison+Milano",st:"Izakaya giapponese contemporanea a Porta Venezia. Yakitori, sake e piatti condivisi.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Yakitori di ottima qualita.","Atmosfera autentica da izakaya giapponese.","Selezione di sake interessante."]}
  ,{n:"Casa Lemon",a:"Via Giulio Uberti 3, Porta Vittoria",pl:2,pr:"€€ · ~40€",cu:"Fusion Peruviana",tg:"internazionale",ws:"https://www.google.com/search?q=Casa+Lemon+Milano",st:"Fusion peruviana a Porta Vittoria. Ceviche, tiradito e cocktail a base di pisco.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:12,l:"12/20"},rv:["Ceviche fresco e ben bilanciato.","Atmosfera colorata e vivace.","Ottimi cocktail a base di pisco."]}
  ,{n:"Le Vent du Nord",a:"Via Sannio 18, Porta Romana",pl:2,pr:"€€ · ~35€",cu:"Belga",tg:"internazionale",ws:"https://www.google.com/search?q=Le+Vent+du+Nord+Milano",st:"Cucina belga autentica a Porta Romana. Moules frites, birre artigianali e atmosfera nordica.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:12,l:"12/20"},rv:["Le moules frites sono il piatto da ordinare.","Selezione di birre belghe eccellente.","Atmosfera accogliente e nordica."]}
];

var favs=new Set(JSON.parse(localStorage.getItem('mifav25')||'[]'));
function saveFavs(){localStorage.setItem('mifav25',JSON.stringify(Array.from(favs)));}

window.toggleFav=function(i){
  var n=R[i].n;
  favs.has(n)?favs.delete(n):favs.add(n);
  saveFavs();
  updateFavCount();render();
};

var S={c:'all',p:'all',g:'all',z:'all',q:'',fav:false};

var mainZones=['brera','navigli','duomo','porta venezia','porta romana','porta garibaldi','moscova','sarpi','tortona','isola'];

function getZone(a){return a.split(',').pop().trim().toLowerCase();}

function maps(a){return'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(a+', Milano');}

function miBadge(r){
  if(r.mi.s>=1)return'<span class="sg mi">'+'\u2B50'.repeat(r.mi.s)+' '+(r.mi.s===1?'Una Stella':r.mi.s+' Stelle')+' <span class="gn">Michelin</span></span>';
  if(r.mi.b)return'<span class="sg mi">\uD83D\uDE0A Bib Gourmand <span class="gn">Michelin</span></span>';
  if(r.mi.g)return'<span class="sg mi" style="background:#f0fff4;border-color:#a8d5b5;color:#276749">\uD83C\uDF3F Green Star <span class="gn">Michelin</span></span>';
  return'<span class="sg mi fd">\u2B50 \u2013 <span class="gn">Michelin</span></span>';
}

function makeCard(r,i){
  var isFav=favs.has(r.n);
  var ta='https://www.tripadvisor.it/Search?q='+encodeURIComponent(r.n+' Milano');
  var rvs='';
  for(var k=0;k<r.rv.length;k++)rvs+='<div class="rv"><span class="st">\u2605\u2605\u2605\u2605\u2605</span><span>'+r.rv[k]+'</span></div>';
  return '<div class="card">'
    +'<button class="favbtn'+(isFav?' on':'')+'" onclick="toggleFav('+i+')">'+( isFav?'\u2764\uFE0F':'\uD83E\uDD0D')+'</button>'
    +'<div class="cb">'
    +'<div class="ctag"><span class="ccu">'+r.cu.toUpperCase()+'</span><span class="cpr">'+r.pr+'</span></div>'
    +'<h2 class="cn"><a href="'+r.ws+'" target="_blank" style="color:inherit;text-decoration:none;">'+r.n+'</a></h2>'
    +'<div class="lks">'
    +'<a href="'+maps(r.a)+'" target="_blank">\uD83D\uDCCD '+r.a+'</a>'
    +'<a href="'+r.ws+'" target="_blank" class="ws">\uD83C\uDF10 Sito web</a>'
    +'<a href="'+ta+'" target="_blank" class="ta">\uD83C\uDF7D TripAdvisor</a>'
    +'</div>'
    +'<div class="sc">'+miBadge(r)
    +'<span class="sg gr">'+'\uD83C\uDF74'.repeat(r.gr.f)+' '+r.gr.l+' <span class="gn">Gambero Rosso</span></span>'
    +'<span class="sg es">\u2615 '+r.es.l+' <span class="gn">L\u2019Espresso</span></span>'
    +'</div>'
    +'<p class="cs">'+r.st+'</p>'
    +'<div class="rvs">'+rvs+'</div>'
    +'</div></div>';
}

function updateFavCount(){
  var n=favs.size;
  document.getElementById('favc').textContent=n>0?'('+n+')':'';
}

function render(){
  var f=[];
  for(var i=0;i<R.length;i++){
    var r=R[i];
    if(S.c!=='all'&&r.tg!==S.c)continue;
    if(S.p!=='all'&&r.pl!==parseInt(S.p))continue;
    if(S.g==='michelin'&&!r.mi.s&&!r.mi.b&&!r.mi.g)continue;
    if(S.g==='gambero'&&r.gr.f<2)continue;
    if(S.g==='espresso'&&r.es.v<15)continue;
    if(S.z!=='all'){var rz=getZone(r.a);if(S.z==='other'){if(mainZones.indexOf(rz)!==-1)continue;}else{if(rz!==S.z)continue;}}
    if(S.fav&&!favs.has(r.n))continue;
    if(S.q){var q=S.q.toLowerCase();var ok=false;var ff=[r.n,r.cu,r.a,r.st];for(var j=0;j<ff.length;j++){if(ff[j].toLowerCase().indexOf(q)>=0){ok=true;break;}}if(!ok)continue;}
    f.push(i);
  }
  document.getElementById('tot').textContent=f.length;
  document.getElementById('rc').textContent=f.length+' risultati';
  var grid=document.getElementById('grid');
  var cards=grid.querySelectorAll('.card');
  for(var k=0;k<cards.length;k++)cards[k].remove();
  document.getElementById('nr').style.display=f.length?'none':'block';
  for(var m=0;m<f.length;m++)grid.insertAdjacentHTML('beforeend',makeCard(R[f[m]],f[m]));
}

document.getElementById('cg').addEventListener('click',function(e){var b=e.target.closest('.fb');if(!b)return;document.querySelectorAll('#cg .fb').forEach(function(x){x.classList.remove('on');});b.classList.add('on');S.c=b.dataset.c;render();});
document.getElementById('pg').addEventListener('click',function(e){var b=e.target.closest('.fb');if(!b)return;document.querySelectorAll('#pg .fb').forEach(function(x){x.classList.remove('on');});b.classList.add('on');S.p=b.dataset.p;render();});
document.getElementById('gg').addEventListener('click',function(e){var b=e.target.closest('.fb');if(!b)return;document.querySelectorAll('#gg .fb').forEach(function(x){x.classList.remove('on');});b.classList.add('on');S.g=b.dataset.g;render();});
document.getElementById('zg').addEventListener('click',function(e){var b=e.target.closest('.fb');if(!b)return;document.querySelectorAll('#zg .fb').forEach(function(x){x.classList.remove('on');});b.classList.add('on');S.z=b.dataset.z;render();});
document.getElementById('favf').addEventListener('click',function(){S.fav=!S.fav;this.classList.toggle('on',S.fav);render();});
document.getElementById('srch').addEventListener('input',function(e){S.q=e.target.value;render();});

updateFavCount();
render();
