var R=[
  {n:"10 11 Portrait",a:"Corso Venezia 11, Porta Venezia",pl:4,pr:"€€€€ · ~100€",cu:"Fine Dining",tg:"italiana",ws:"https://www.google.com/search?q=10%2011%20Portrait%20ristorante%20Milano",st:"L’hotel Portrait ospita uno dei ristoranti piu glamour di Milano. Cucina italiana d’autore.",mi:{s:0,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:16,l:"16/20"},rv:["Eleganza e sostanza in equilibrio perfetto.","La terrazza sul Corso Venezia e magnifica d’estate.","Carta vini di grande profondita con etichette rare."]},
  {n:"Abba",a:"Via Varesina 177, Certosa",pl:3,pr:"€€€ · ~65€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://www.google.com/search?q=Abba%20ristorante%20Milano",st:"Cucina italiana contemporanea a Brera. Chef giovane: stagionalita e territorio.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Cucina matura e precisa per uno chef cosi giovane.","Il risotto varia con le stagioni: sempre cremoso e saporito.","Ambiente raffinato senza essere formale."]},
  {n:"Akiro",a:"Via della Moscova 50, Brera",pl:2,pr:"€€ · ~40€",cu:"Giapponese",tg:"giapponese",ws:"https://www.google.com/search?q=Akiro%20ristorante%20Milano",st:"Ristorante giapponese autentico vicino alla Stazione Centrale. Ramen, gyoza e piatti della cucina nipponica preparati con tecnica e ingredienti giapponesi. Frequentato dalla comunita giapponese di Milano.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:14,l:"14/20"},rv:["Il ramen di Akiro e tra i migliori di Milano: brodo ricco e noodles freschi fatti in casa.","Frequentato dalla comunita giapponese: la garanzia di autenticita definitiva.","Gyoza croccanti e tonkotsu profumato: la cucina giapponese a Milano nella sua versione piu onesta."]},
  {n:"Al Garghet",a:"Via Selvanesco 36, Rozzano",pl:3,pr:"€€€ · ~65€",cu:"Milanese",tg:"italiana",ws:"https://www.google.com/search?q=Al%20Garghet%20ristorante%20Milano",st:"Trattoria storica in un cascinale lombardo. Cucina milanese autentica con spazio estivo.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Vale il viaggio fuori citta. Cucina milanese vera, non da turista.","D’estate si mangia sotto la pergola con vista sul verde.","Il fagiano in salmi e memorabile."]},
  {n:"Allangolare",a:"Via Plinio 46, Porta Venezia",pl:2,pr:"€€ · ~40€",cu:"Italiana Moderna",tg:"italiana",ws:"https://www.google.com/search?q=Allangolare%20ristorante%20Milano",st:"Osteria moderna a Porta Venezia. Cucina di stagione legata al territorio.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Il posto di quartiere perfetto: buono, onesto, senza pretese.","La tartare e tra le migliori della zona.","La pasta al ragu bianco non la trovi da nessun’altra parte."]},
  {n:"Anima",a:"Via Carlo de Cristoforis 6, Porta Garibaldi",pl:4,pr:"€€€€ · ~140€",cu:"Alta Cucina Creativa",tg:"italiana",ws:"https://www.google.com/search?q=Anima%20ristorante%20Milano",st:"Una stella Michelin firmata Enrico Bartolini nel Milano Verticale. Chef resident Michele Cobuzzi porta la Puglia a Milano con tecnica e creativita.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["Cucina pugliese elevata all alta gastronomia: storia personale nel piatto.","I Bottoni di gallina nostrana con cime di rapa sono tra i piatti piu riusciti della citta.","Sommelier e sala tra i migliori di Milano."]},
  {n:"Antica Trattoria della Pesa",a:"Viale Pasubio 10, Moscova",pl:3,pr:"€€€ · ~65€",cu:"Milanese Storica",tg:"italiana",ws:"https://www.google.com/search?q=Antica%20Trattoria%20della%20Pesa%20ristorante%20Milano",st:"Dal 1880, una delle trattorie piu antiche di Milano. Cucina lombarda classica.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Un pezzo di storia di Milano. Si torna indietro di un secolo.","La cotoletta alla milanese e quella originale. Il riferimento assoluto.","Risotto alla milanese e ossobuco che non deludono mai."]},
  {n:"Autem",a:"Via Serviliano Lattuada 2, Porta Romana",pl:3,pr:"€€€ · ~70€",cu:"Italiana Creativa",tg:"italiana",ws:"https://www.google.com/search?q=Autem%20ristorante%20Milano",st:"Cucina italiana reinterpretata con tecnica e creativita. Vini naturali di grande carattere.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Cucina ambiziosa e centrata. Ogni piatto ha una logica chiara.","Il menu degustazione e il modo migliore per vivere Autem.","Una delle migliori esperienze gastronomiche della stagione."]},
  {n:"Azabu 10",a:"Via San Glicerio 6, Bicocca",pl:4,pr:"€€€€ · ~120€",cu:"Sushi Omakase",tg:"giapponese",ws:"https://www.google.com/search?q=Azabu%2010%20ristorante%20Milano",st:"Chef Andrea Arcieri porta a Milano un omakase di 22-25 portate tra pesce frollato e tecnica edomae. Premio Novita Gambero Rosso Sushi 2025.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Un talento quasi geniale. Il pesce frollato e un altra dimensione del sushi.","Tonno ikejime e abbinamenti arditi ma centratissimi.","Il banco da 10 posti e un rito: ogni portata e un piccolo capolavoro."]},
  {n:"Ba",a:"Via Bagnera 2, Duomo",pl:3,pr:"€€€ · ~60€",cu:"Asiatica Fusion",tg:"asiatica",ws:"https://www.google.com/search?q=Ba%20ristorante%20Milano",st:"Viaggio gastronomico attraverso le cucine dell’Asia in uno dei vicoli piu antichi di Milano.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Dim sum di livello autentico: delicati e saporosi.","Atmosfera unica in una delle strade piu antiche della citta.","Cucina fusion che non tradisce le origini asiatiche."]},
  {n:"Bauscia",a:"Via dell Orso 2, Brera",pl:3,pr:"€€€ · ~65€",cu:"Milanese Contemporanea",tg:"italiana",ws:"https://www.google.com/search?q=Bauscia%20ristorante%20Milano",st:"Cucina milanese rivisitata nel cuore di Brera. Splendido giardino interno. Risotto alla milanese con midollo, cotoletta.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:13,l:"13/20"},rv:["Il risotto alla milanese mantecato con midollo: zafferano intenso e cremoso.","La cotoletta con salsa agrumata e il secondo piatto di riferimento.","Il giardino interno fiorito d estate e tra i posti piu belli di Brera."]},
  {n:"Bela Tusa",a:"Via Procaccini 37, Sarpi",pl:2,pr:"€€ · ~35€",cu:"Piemontese",tg:"italiana",ws:"https://www.google.com/search?q=Bela%20Tusa%20ristorante%20Milano",st:"Trattoria piemontese autentica. Tajarin, vitello tonnato. Bib Gourmand.",mi:{s:0,b:1,g:0},gr:{f:2,l:"Due Forchette"},es:{v:13,l:"13/20"},rv:["I tajarin al ragu d’anatra sono uno dei piatti piu buoni di Milano.","Il vitello tonnato qui e quello vero: carne tenera, salsa cremosa.","Prezzi contenuti per un’esperienza genuina."]},
  {n:"Bice Restaurant",a:"Via Borgospesso 12, San Babila",pl:4,pr:"€€€€ · ~90€",cu:"Italiana Classica",tg:"italiana",ws:"https://www.google.com/search?q=Bice%20Restaurant%20ristorante%20Milano",st:"Storico ristorante milanese fondato nel 1926 in zona San Babila. Cucina italiana tradizionale in ambiente elegante.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Un istituzione di Milano dal 1926: la cucina italiana nell accezione piu nobile.","Ambiente elegante, discreto e senza tempo. Perfetto per cene importanti.","La tradizione rispettata senza eccessi."]},
  {n:"Bottega Lucia",a:"Via P. Castaldi 16, Repubblica",pl:3,pr:"€€€ · ~55€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://www.google.com/search?q=Bottega%20Lucia%20ristorante%20Milano",st:"Bistrot dal fascino caldo. Cucina italiana gustosa e cocktail bar curato.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:13,l:"13/20"},rv:["Atmosfera bistrot autentica. Il cibo e curato senza fronzoli.","La terrazza estiva e uno dei posti piu piacevoli di Milano.","Il cocktail bar abbina i drink ai piatti con cura."]},
  {n:"Brolo",a:"Via Palermo 13, Brera",pl:3,pr:"€€€ · ~60€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://www.google.com/search?q=Brolo%20ristorante%20Milano",st:"Cucina italiana contemporanea ispirata all orto e alla stagionalita. Ingredienti di piccoli produttori, ambiente caldo e accogliente.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Cucina che rispetta la stagionalita con risultati sempre convincenti.","I vegetali sono protagonisti assoluti, trattati con grande rispetto.","Un posto genuino e piacevole, lontano dalle mode."]},
  {n:"Brolo Orto con Cucina",a:"Via E. Oldofredi 2, Porta Garibaldi",pl:3,pr:"€€€ · ~65€",cu:"Vegetariana",tg:"italiana",ws:"https://www.google.com/search?q=Brolo%20Orto%20con%20Cucina%20ristorante%20Milano",st:"L’orto come fonte d’ispirazione. Cucina vegetale d’autore. Michelin Green Star.",mi:{s:0,b:0,g:1},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["La cucina vegetale qui e all’altezza di qualsiasi stellato.","Menu degustazione: viaggio attraverso le stagioni dell’orto.","Giardino interno meraviglioso. D’estate e magico."]},
  {n:"Cantina Piemontese",a:"Via Laghetto 2, Duomo",pl:3,pr:"€€€ · ~60€",cu:"Piemontese",tg:"italiana",ws:"https://www.google.com/search?q=Cantina%20Piemontese%20ristorante%20Milano",st:"La cucina piemontese nel centro di Milano. Vini delle Langhe, tartufo, fonduta.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Il menu invernale con tartufo bianco d’Alba vale ogni euro.","La bagna cauda e quella autentica.","La cantina con Barolo e Barbaresco e straordinaria."]},
  {n:"Capra e Cavoli",a:"Via Pastrengo 18, Isola",pl:3,pr:"€€€ · ~50€",cu:"Vegetariana Creativa",tg:"vegetariano",ws:"https://www.google.com/search?q=Capra+e+Cavoli+ristorante+Milano",st:"Loft ristorante nel quartiere Isola con arredamento shabby-chic a casette di legno. Cucina vegetariana e vegana creativa con qualche piatto di pesce, stagionale e di alta qualita. Barbara Clementina Ferrario porta in tavola ricette della tradizione rivisitate con materie prime selezionate. Prenotare indispensabile.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Un loft ristorante unico nel suo genere: casette di legno che creano angoli intimi e romantici nel cuore dell Isola.","Cucina vegetariana e vegana di altissimo livello, con piatti creativi stagionali e materie prime selezionate. Qualche proposta di pesce.","Valutazione TheFork 9.4: uno dei preferiti di Milano. Atmosfera calda e informale, servizio attento. Chiuso il lunedi."]},
  {n:"Casa Camperio",a:"Via Giuliani 6, Duomo",pl:3,pr:"€€€ · ~60€",cu:"Italiana Fusion",tg:"italiana",ws:"https://www.google.com/search?q=Casa%20Camperio%20ristorante%20Milano",st:"Michelin Plate 2025. Cucina italiana con tocchi giapponesi, cucina a vista, giardino. Chef Roberto Conti (ex Trussardi alla Scala).",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Il risotto alla milanese accanto al maki roll: fusione che funziona.","Servizio di rara gentilezza. Uno degli spazi piu eleganti del centro.","Il cocktail bar abbina drink e piatti con intelligenza."]},
  {n:"Casa Tobago",a:"Via Melzo 22, Porta Venezia",pl:2,pr:"€€ · ~45€",cu:"Fusion Caraibica",tg:"internazionale",ws:"https://www.google.com/search?q=Casa%20Tobago%20ristorante%20Milano",st:"Cucina fusion caraibica e latinoamericana. Cocktail tropicali e atmosfera festosa.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:12,l:"12/20"},rv:["I cocktail sono straordinari e originali.","La cucina e una festa di sapori: autenticita e abbondanza.","La ceviche fusion e sorprendentemente ben eseguita."]},
  {n:"Casazul",a:"Via Vigevano 6, Navigli",pl:2,pr:"€€ · ~40€",cu:"Latinoamericana",tg:"internazionale",ws:"https://www.google.com/search?q=Casazul%20ristorante%20Milano",st:"Colori e sapori latinoamericani sui Navigli. Cucina fusion con influenze peruviane e messicane.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:12,l:"12/20"},rv:["Il ceviche e fresco e ben bilanciato tra acido e piccante.","Atmosfera festosa e vivace, perfetto per una serata informale.","Le empanadas sono croccanti e ben ripiene."]},
  {n:"Cavoli a Merenda",a:"Via Melzo 10, Porta Venezia",pl:2,pr:"€€ · ~40€",cu:"Vegetariana",tg:"italiana",ws:"https://www.google.com/search?q=Cavoli%20a%20Merenda%20ristorante%20Milano",st:"Cucina vegetariana creativa che dimostra come si possa mangiare benissimo senza carne.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Finalmente un vegetariano che non sembra un sacrificio.","Anche i carnivori escono soddisfatti.","Ottimo rapporto qualita/prezzo per il quartiere."]},
  {n:"Coke Tales",a:"Via B. Marcello 34, Porta Venezia",pl:2,pr:"€€ · ~35€",cu:"Cocktail Bar",tg:"internazionale",ws:"https://www.google.com/search?q=Coke%20Tales%20ristorante%20Milano",st:"Cocktail bar con cucina fusion. Il cocktail e al centro, la cucina lo accompagna.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:12,l:"12/20"},rv:["Cocktail di livello altissimo. Il bartender crea abbinamenti originali.","La cucina e sorprendentemente buona per un cocktail bar.","Uno dei migliori indirizzi di Porta Venezia per iniziare la serata."]},
  {n:"Confine",a:"Piazza XXIV Maggio 8, Navigli",pl:3,pr:"€€€ · ~60€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://www.google.com/search?q=Confine%20ristorante%20Milano",st:"Sulla Darsena, cucina italiana contemporanea con vista. Ingredienti locali.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["La posizione sulla Darsena e magnifica.","Il risotto alle erbe selvatiche lo ricordero a lungo.","Ottima selezione di vini naturali."]},
  {n:"Contraste",a:"Via Meda 2, Porta Romana",pl:5,pr:"€€€€€ · ~180€",cu:"Alta Cucina",tg:"italiana",ws:"https://www.google.com/search?q=Contraste%20ristorante%20Milano",st:"Una stella Michelin in un palazzo storico. Lo chef Matias Perdomo porta una cucina visionaria che sfida le convenzioni.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:18,l:"18/20"},rv:["Una cucina che sorprende e destabilizza nel senso migliore.","L’ambiente e tra i piu belli di Milano: palazzo storico restaurato con gusto.","Il menu degustazione: ogni portata ha una logica e una tecnica straordinaria."]},
  {n:"Creda",a:"Via Orti 12, Porta Romana",pl:2,pr:"€€ · ~30€",cu:"Campana",tg:"italiana",ws:"https://www.google.com/search?q=Creda%20ristorante%20Milano",st:"Gastronomia popolare: cucina partenopea autentica dalla colazione alla cena. Banco asporto e sala ristorante.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:12,l:"12/20"},rv:["Cucina napoletana vera a Milano: sapori di casa, nessuna concessione alla moda.","Il bancone gastronomia e un ancora di qualita in zona Porta Romana.","Dalla colazione al dopocena: formato versatile e genuino."]},
  {n:"Crosta",a:"Via Felice Bellotti 13, Porta Venezia",pl:1,pr:"€ · ~20€",cu:"Pizzeria Artigianale",tg:"pizzeria",ws:"https://www.google.com/search?q=Crosta+pizzeria+Milano+Bellotti",st:"Panificio-pizzeria nata nel 2018 dall incontro tra il pizzaiolo Simone Lombardi (ex Dry) e il panettiere Giovanni Mineo (allievo di Longoni). Di giorno pizza alla pala e pane artigianale, la sera pizza tonda gourmet con impasto leggero e ingredienti di qualita. Segnalata da 50 Top Pizza. Due sedi: Bellotti 13 e Via Melzo 5.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Ibrido unico tra panificio e pizzeria: di giorno pane da forno artigianale e pizza alla pala, la sera pizza tonda gourmet con impasto soffice e ben cotto.","Simone Lombardi ex Dry e Giovanni Mineo allievo di Longoni: due maestri per una delle pizze piu interessanti di Milano.","Segnalata da 50 Top Pizza, frequentata tutto il giorno dalla colazione fino a sera. Impasto leggero, topping con materie prime selezionate."]},
  {n:"Da Berti",a:"Via Solari 32, Tortona",pl:2,pr:"€€ · ~38€",cu:"Italiana Tradizionale",tg:"italiana",ws:"https://www.google.com/search?q=Da%20Berti%20ristorante%20Milano",st:"Trattoria milanese classica, vino sfuso, cucina senza mode.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:12,l:"12/20"},rv:["Un’ancora di tradizione nel quartiere Tortona.","Semplicita e qualita in ogni piatto.","L’animella impanata e un capolavoro di cucina di recupero."]},
  {n:"Denis Pizza di Montagna",a:"Via Statuto 16, Moscova",pl:2,pr:"€€ · ~35€",cu:"Pizza di Montagna",tg:"pizza",ws:"https://www.google.com/search?q=Denis%20Pizza%20di%20Montagna%20ristorante%20Milano",st:"Denis Lovatel porta a Milano la sua pizza di montagna: impasto croccante e leggero, ingredienti alpini. 50 Top Pizza.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Una pizza che racconta le Dolomiti ad ogni morso. Croccante, leggera, memorabile.","Gli ingredienti di montagna sono di qualita rara.","Uno dei locali piu belli di Moscova."]},
  {n:"Deposito Enoteca",a:"Via della Moscova 10, Moscova",pl:3,pr:"€€€ · ~60€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://www.google.com/search?q=Deposito%20Enoteca%20ristorante%20Milano",st:"Enoteca e ristorante nel cuore di Moscova. Cucina italiana contemporanea con una delle selezioni di vini piu interessanti di Milano: oltre 800 etichette, focus su artigianali e naturali.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["La carta dei vini e straordinaria: 800 etichette con focus su piccoli produttori e vini naturali.","La cucina italiana segue la stagionalita ed e all altezza della selezione di vini.","Uno degli indirizzi piu interessanti per gli appassionati di vino a Milano."]},
  {n:"Dry Milano",a:"Via Solferino 33, Brera",pl:2,pr:"€€ · ~40€",cu:"Pizza Gourmet",tg:"pizza",ws:"https://www.google.com/search?q=Dry%20Milano%20ristorante%20Milano",st:"Pioniere della pizza gourmet a Milano. Bib Gourmand.",mi:{s:0,b:1,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["La pizza qui e un’altra cosa rispetto alla media milanese.","La cocktail list e tra le migliori di Milano.","Un’istituzione che ha cambiato la cultura gastronomica milanese."]},
  {n:"El Carnicero",a:"Via Spartaco 31, Porta Romana",pl:3,pr:"€€€ · ~65€",cu:"Steakhouse Argentina",tg:"internazionale",ws:"https://www.google.com/search?q=El%20Carnicero%20ristorante%20Milano",st:"Dal 2013 il riferimento milanese per la carne di qualita. Tre sedi in citta, carni da tutto il mondo alla griglia.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:13,l:"13/20"},rv:["La Entrana argentina e succosa e perfettamente cotta sulla brace.","La provoleta e gia un capolavoro.","Il Tomahawk di Black Angus australiano vale ogni euro."]},
  {n:"El Porteno",a:"Via G. Galeazzo 25, Ticinese",pl:3,pr:"€€€ · ~60€",cu:"Argentina",tg:"internazionale",ws:"https://www.google.com/search?q=El%20Porteno%20ristorante%20Milano",st:"Il tempio dell asado argentino a Milano dal 2000. Carni eccellenti, atmosfera autentica. Tre sedi in citta.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:13,l:"13/20"},rv:["Il bife de lomo argentino e tenero e saporito come a Buenos Aires.","L asado cotto su brace viva: tecnica e rispetto per la materia prima.","Atmosfera calda e conviviale, perfetta per cene in gruppo."]},
  {n:"Emoraya",a:"Via Vigevano 20, Navigli",pl:2,pr:"€€ · ~40€",cu:"Thai",tg:"asiatica",ws:"https://www.google.com/search?q=Emoraya%20ristorante%20Milano",st:"Cucina thai autentica ai Navigli. Sapori intensi, erbe fresche, ricette tradizionali eseguite con materie prime di qualita.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Il miglior thai di Milano: sapori autentici e spezie bilanciate.","Il pad thai e il curry verde sono i piatti di riferimento.","Ambiente informale e vivace, perfetto per una serata ai Navigli."]},
  {n:"Eppol Milano",a:"Via Ettore Ponti 35, Navigli",pl:3,pr:"€€€ · ~60€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://www.google.com/search?q=Eppol%20Milano%20ristorante%20Milano",st:"Ristorante contemporaneo sui Navigli. Cucina che valorizza il territorio lombardo.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Cucina lombarda reinterpretata con intelligenza.","Carta dei vini tra le migliori dei Navigli.","Servizio professionale e giovane, con vera passione."]},
  {n:"Fioraio Bianchi",a:"Via Montebello 7, Moscova",pl:3,pr:"€€€ · ~60€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://www.google.com/search?q=Fioraio%20Bianchi%20ristorante%20Milano",st:"Il ristorante dentro la storica fioreria di Brera. Atmosfera unica tra fiori e luci calde.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Tra i fiori e le luci soffuse si crea vera magia.","Per occasioni speciali e il posto perfetto a Milano.","La carta dei vini e curata con intelligenza."]},
  {n:"Food Writers",a:"Via Vigevano 28, Navigli",pl:2,pr:"€€ · ~40€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://www.google.com/search?q=Food%20Writers%20ristorante%20Milano",st:"Ristorante che racconta il cibo attraverso storie e prodotti selezionati.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Ogni piatto racconta una storia di produttori e territori.","Selezione di formaggi e salumi tra le migliori di Milano.","Un posto che ama il cibo in modo autentico."]},
  {n:"Forneria Metropolitana",a:"Via Anfossi 13, Porta Romana",pl:1,pr:"€ · ~20€",cu:"Bakery",tg:"italiana",ws:"https://www.google.com/search?q=Forneria%20Metropolitana%20ristorante%20Milano",st:"Panificio artigianale con cucina. Pane di qualita eccezionale e panini gourmet.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:12,l:"12/20"},rv:["Il pane e straordinario: crosta, alveolatura, profumo.","I panini sono costruiti con intelligenza e ingredienti di qualita.","La focaccia calda del mattino e un motivo per svegliarsi presto."]},
  {n:"Futura Pizzeria Romana",a:"Via Pietro Borsieri 28, Isola",pl:2,pr:"€€ · ~30€",cu:"Pizza Romana",tg:"pizza",ws:"https://www.google.com/search?q=Futura%20Pizzeria%20Romana%20ristorante%20Milano",st:"La pizza tonda romana di Luca Pezzetta nel quartiere Isola. Sottile, leggera, bordo bruciato. 50 Top Pizza.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["La tonda romana piu autentica di Milano: sottile, croccante, bordo bruciacchiato.","Luca Pezzetta e il miglior pizzaiolo romano arrivato a Milano.","Diventata subito un culto: prenotazione sempre difficilissima."]},
  {n:"Gio Gio s",a:"Via Caminadella 7, Duomo",pl:3,pr:"€€€ · ~60€",cu:"Mediterranea Cosmopolita",tg:"internazionale",ws:"https://www.google.com/search?q=Gio%20Gio%20s%20ristorante%20Milano",st:"Aperto aprile 2026. Chef Raphael Duntoye (Londra, Dubai). Cucina mediterranea contemporanea per la condivisione. Giardino urbano.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["La tartare di tonno con agrumi e gia un piatto cult della nuova Milano.","Spazio unico: giardino urbano con velluti e piante botaniche.","Il Mediterraneo con occhio cosmopolita."]},
  {n:"Gong",a:"Corso Concordia 8, Porta Venezia",pl:3,pr:"€€€ · ~70€",cu:"Cinese Contemporanea",tg:"asiatica",ws:"https://www.google.com/search?q=Gong%20ristorante%20Milano",st:"La cucina cinese di lusso a Milano. Design orientale di gran classe.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Il Peking Duck e tra i migliori fuori dalla Cina.","Ambiente di grande fascino, perfetto per ospiti importanti.","Dim sum di qualita superiore rispetto alla media milanese."]},
  {n:"Hazama",a:"Via Disciplini 5, Duomo",pl:4,pr:"€€€€ · ~100€",cu:"Giapponese Omakase",tg:"giapponese",ws:"https://www.google.com/search?q=Hazama%20ristorante%20Milano",st:"Omakase giapponese di alta precisione nel centro di Milano. Pesce freschissimo, tecnica edomae, esperienza intima al bancone.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Un omakase di grande livello: pesce eccellente e tecnica impeccabile.","Atmosfera raccolta e serena, ogni portata e una piccola opera.","Tra i migliori indirizzi giapponesi di nuova generazione a Milano."]},
  {n:"Horto",a:"Via San Protaso 5, Cordusio",pl:5,pr:"€€€€€ · ~185€",cu:"Alta Cucina Sostenibile",tg:"italiana",ws:"https://www.google.com/search?q=Horto%20ristorante%20Milano",st:"Una stella Michelin e Green Star sul rooftop di The Medelan. Norbert Niederkofler: fornitori entro un ora da Milano, stagionalita assoluta.",mi:{s:1,b:0,g:1},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["La tartare di anguria con caviale di storione e straordinaria.","Il risotto alle fragole fermentate e memorabile. La terrazza con Madonnina e unica.","Cucina etica che non sacrifica il gusto. Uno dei migliori di Milano."]},
  {n:"Ichikawa",a:"Via Fiori Chiari 1, Brera",pl:4,pr:"€€€€ · ~90€",cu:"Giapponese Sushi",tg:"giapponese",ws:"https://www.google.com/search?q=Ichikawa%20ristorante%20Milano",st:"Sushi bar di riferimento a Brera, pesce di altissima qualita e filosofia tradizionale.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Il pesce e di qualita eccezionale, freschissimo e trattato con rispetto assoluto.","Pochi tavoli, esperienza intima e personalizzata. Prenotazione indispensabile.","Il nigiri di tonno e uno dei migliori fuori dal Giappone."]},
  {n:"Inno",a:"Piazza Duomo ang. Via G. Mazzini 2, Duomo",pl:4,pr:"€€€€ · ~100€",cu:"Fusion Messico-Giappone",tg:"internazionale",ws:"https://www.google.com/search?q=Inno%20ristorante%20Milano",st:"Aperto aprile 2026. Al secondo piano con vista spettacolare sul Duomo. Chef Marcos Cardoso fonde cucina messicana e giapponese.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["La vista sul Duomo dalla terrazza e probabilmente la migliore di Milano.","Pollo in tempura con gelato al mango: abbinamento audace che sorprende.","Design raffinato. Milano internazionale al massimo."]},
  {n:"Iyo",a:"Via Piero della Francesca 74, Municipio 8",pl:4,pr:"€€€€ · ~100€",cu:"Giapponese Contemporanea",tg:"giapponese",ws:"https://www.google.com/search?q=Iyo%20ristorante%20Milano",st:"Il primo ristorante giapponese in Italia a ottenere una stella Michelin. Cucina nikkei di altissimo livello.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["Una stella Michelin meritatissima. La cucina giapponese raggiunge vette eccezionali.","Il menu omakase e un viaggio tra Giappone e Italia che sorprende ad ogni portata.","Ambiente sofisticato e servizio impeccabile."]},
  {n:"Jiao10",a:"Via Paolo Sarpi 10, Chinatown",pl:1,pr:"€ · ~22€",cu:"Dumplings",tg:"asiatica",ws:"https://www.google.com/search?q=Jiao10%20ristorante%20Milano",st:"Specialisti dei jiaozi in tutte le forme. Qualita rara a questi prezzi.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:11,l:"11/20"},rv:["I jiaozi al vapore con gamberi e bambu: delicatezza assoluta.","La pasta tirata sottile come si deve.","Prezzi da street food, qualita da ristorante serio."]},
  {n:"Kaja Bistrot",a:"Via Vigevano 18, Navigli",pl:2,pr:"€€ · ~45€",cu:"Scandinava",tg:"internazionale",ws:"https://www.google.com/search?q=Kaja%20Bistrot%20ristorante%20Milano",st:"Cucina nordica a Milano: minimalismo, ingredienti d’eccellenza e tecnica scandinava.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Una ventata di freschezza nel panorama milanese. Cucina nordica autentica.","Il salmone marinato in casa con aneto e inaspettatamente eccellente.","La carta dei vini nordici e naturali e una scoperta continua."]},
  {n:"La Cantina di Manuela",a:"Via C. Poerio 3, Porta Venezia",pl:2,pr:"€€ · ~40€",cu:"Enoteca con Cucina",tg:"italiana",ws:"https://www.google.com/search?q=La%20Cantina%20di%20Manuela%20ristorante%20Milano",st:"Enoteca con cucina a Porta Venezia. Selezione di vini di piccoli produttori, taglieri curati.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:13,l:"13/20"},rv:["Una delle migliori selezioni di vini naturali e artigianali di Milano.","I taglieri con salumi e formaggi selezionati sono il modo perfetto per iniziare la serata.","Ambiente accogliente e informale, perfetto per una cena in compagnia."]},
  {n:"La Latteria",a:"Via San Marco 24, Brera",pl:2,pr:"€€ · ~35€",cu:"Italiana Classica",tg:"italiana",ws:"https://www.google.com/search?q=La%20Latteria%20ristorante%20Milano",st:"Piccola trattoria storica a Brera. Menu scritto a mano su lavagna. Bib Gourmand.",mi:{s:0,b:1,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["La latteria e un pezzo di Milano che non si dovrebbe mai perdere.","La pasta al pomodoro migliore del 90% dei ristoranti stellati.","L’esperienza vale qualsiasi sacrificio per ottenere un tavolo."]},
  {n:"Langosteria",a:"Via Savona 10, Navigli",pl:5,pr:"€€€€€ · ~150€",cu:"Pesce Fine Dining",tg:"pesce",ws:"https://www.google.com/search?q=Langosteria%20ristorante%20Milano",st:"Il tempio del pesce di lusso dal 2007. Una stella Michelin.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:18,l:"18/20"},rv:["Il plateau di crudi e senza rivali a Milano.","Langoustine, astice, ostriche: qualita costante nel tempo.","Cantina straordinaria: champagne e grandi bianchi italiani."]},
  {n:"Le Nove Scodelle",a:"Via Casale 5, Porta Venezia",pl:2,pr:"€€ · ~35€",cu:"Cinese Regionale",tg:"asiatica",ws:"https://www.google.com/search?q=Le%20Nove%20Scodelle%20ristorante%20Milano",st:"Cucina cinese regionale autentica. Piatti dello Yunnan e del Sichuan con ingredienti importati.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["La cucina cinese piu autentica di Milano. Sapori profondi e ingredienti rari.","I noodles dello Yunnan fatti a mano sono un piatto memorabile.","Un posto che ha cambiato la percezione della cucina cinese a Milano."]},
  {n:"Lubna",a:"Via Argelati 19, Navigli",pl:2,pr:"€€ · ~35€",cu:"Libanese",tg:"internazionale",ws:"https://www.google.com/search?q=Lubna%20ristorante%20Milano",st:"La cucina libanese nella sua forma piu autentica. Meze condivisi, pita fresca, hummus.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:12,l:"12/20"},rv:["Il kibbeh e perfetto: croccante fuori, saporito dentro.","L’hummus con burro e pinoli e una rivelazione.","Il fattoush freschissimo. Il miglior libanese della citta."]},
  {n:"Luceferma",a:"Via Privata Bugatti 9, Ortica",pl:3,pr:"€€€ · ~60€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://www.google.com/search?q=Luceferma%20ristorante%20Milano",st:"Ristorante contemporaneo nel quartiere Ortica a Milano. Cucina italiana di ricerca con ingredienti selezionati, cantina curata, ambiente informale e ricercato. Uno degli indirizzi piu interessanti della nuova Milano.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Uno dei ristoranti piu interessanti della nuova Milano: cucina di ricerca senza pretese.","Il quartiere Ortica e la Milano autentica e creativa: Luceferma ne e l anima gastronomica.","Cantina curata con vini naturali e italiani di qualita: ogni visita e una scoperta."]},
  {n:"Manna",a:"Via L. Cusani 1, Brera",pl:3,pr:"€€€ · ~55€",cu:"Italiana Creativa",tg:"italiana",ws:"https://www.google.com/search?q=Manna%20ristorante%20Milano",st:"Cucina italiana contemporanea creativa. Ingredienti di stagione e tecniche moderne.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Menu stagionale: ogni visita e una nuova esperienza.","La pasta fresca fatta in casa con farine di qualita eccelsa.","Servizio giovane e preparato, racconta ogni piatto con passione."]},
  {n:"Maoji Street Food",a:"Via Paolo Sarpi 22, Chinatown",pl:1,pr:"€ · ~20€",cu:"Sichuan",tg:"asiatica",ws:"https://www.google.com/search?q=Maoji%20Street%20Food%20ristorante%20Milano",st:"Il vero street food del Sichuan in Paolo Sarpi. Piccante, aromatico, autentico.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:11,l:"11/20"},rv:["Il mapo tofu piu autentico fuori dalla Cina.","I noodles freddi al sesamo con pepe di Sichuan sono magnifici.","Prezzi da street food, qualita da ristorante serio."]},
  {n:"Masayume",a:"Via Garigliano 6, Isola",pl:2,pr:"€€ · ~28€",cu:"Izakaya Contemporanea",tg:"giapponese",ws:"https://www.google.com/search?q=Masayume+ristorante+Milano",st:"Izakaya moderna nel quartiere Isola con estetica urbana ispirata a Shinjuku: neon, graffiti, cultura pop giapponese. Il ramen con brodo tori paitan cotto 10 ore e il gyoza fatto a mano sono il cuore del menu.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:14,l:"14/20"},rv:["Una izakaya autentica nel quartiere Isola con un design che richiama i vicoli di Shinjuku.","Il ramen con brodo tori paitan cotto 10 ore e il chashu marinato 48h: cura e passione totale.","Gyoza fatti a mano, bao, katsusando: una cucina giapponese informale e di grande qualita."]},
  {n:"Mater Bistrot",a:"Via Pasquale Sottocorno 1, Porta Vittoria",pl:2,pr:"€€ · ~40€",cu:"Naturale",tg:"italiana",ws:"https://www.google.com/search?q=Mater%20Bistrot%20ristorante%20Milano",st:"Bistrot dedicato ai prodotti naturali. Cucina vegetale, vini naturali, approccio etico.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Un posto che fa bene e fa del bene. Cucina vegetale di qualita.","La cura per la provenienza degli ingredienti si sente nel gusto.","I dessert sono sorprendentemente buoni e creativi."]},
  {n:"Meze",a:"Via Pasquale Sottocorno 19/A, Porta Vittoria",pl:2,pr:"€€ · ~35€",cu:"Mediorientale",tg:"internazionale",ws:"https://www.google.com/search?q=Meze%20ristorante%20Milano",st:"Viaggio culinario nel Medioriente. Meze condivisi, spezie profumate.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:12,l:"12/20"},rv:["I meze sono abbondanti e autentici. L’hummus fatto in casa e un’altra categoria.","Perfetto per gruppi: tutto da condividere, prezzi corretti.","Il baklava fatto in casa e il miglior finale possibile."]},
  {n:"Misoya",a:"Via Solferino 41, Brera",pl:2,pr:"€€ · ~25€",cu:"Ramen Bar",tg:"giapponese",ws:"https://www.google.com/search?q=Misoya+ramen+Milano",st:"Primo ristorante europeo della celebre catena giapponese Misoya, segnalata dalla guida Michelin a New York e Montreal. Specializzata nel ramen miso: Hokkaido Miso, Tokyo Miso, Vege Miso. Miso importato direttamente dal Giappone.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:14,l:"14/20"},rv:["Il primo ristorante Misoya in Europa: la catena giapponese e segnalata dalla Michelin a New York.","Il ramen miso con brodo di pollo e maiale e miso importato dal Giappone: autenticita totale.","Hokkaido Miso, Tokyo Miso, Vege Miso: tre versioni di un ramen che non si dimentica facilmente."]},
  {n:"Mitu",a:"Via Savona 11, Tortona",pl:2,pr:"€€ · ~40€",cu:"Messicana",tg:"internazionale",ws:"https://www.google.com/search?q=Mitu%20ristorante%20Milano",st:"La cucina messicana seria che Milano aspettava. Tortillas fatte a mano.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["I tacos al pastor con ananas sono quelli originali.","La carta del mezcal e straordinaria.","Le tortillas fatte a mano fanno tutta la differenza."]},
  {n:"Miyabi",a:"Corso Monforte 26, San Babila",pl:3,pr:"€€€ · ~50€",cu:"Giapponese Contemporaneo",tg:"giapponese",ws:"https://www.google.com/search?q=Miyabi+ristorante+Milano",st:"Ristorante giapponese autentico a San Babila. Chef Katsuhiko Ochiai porta la tradizione di Osaka e Tokyo con sushi di altissima qualita, uramaki creativi, chirashi e piatti caldi. Bancone a vista su due livelli.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Chef Katsuhiko Ochiai viene da Shizuoka e ha lavorato nei migliori ristoranti giapponesi di Tokyo.","Il sushi di Miyabi e tra i piu autentici di Milano: pesce freschissimo e tecniche tradizionali nipponiche.","Sempre pieno sia a pranzo che a cena: prenotare con largo anticipo e indispensabile."]},
  {n:"Miyama",a:"Via Bazzini 37, Citta Studi",pl:3,pr:"€€€ · ~70€",cu:"Giapponese",tg:"giapponese",ws:"https://www.google.com/search?q=Miyama%20ristorante%20Milano",st:"Cucina kaiseki tradizionale. Una stella Michelin.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["Il miglior giapponese tradizionale di Milano senza dubbio.","Sashimi servito con rispetto. Il tonno e straordinario.","Si percepisce subito il rispetto per la tradizione."]},
  {n:"Mogo",a:"Via Bergamo 6, Porta Venezia",pl:1,pr:"€ · ~18€",cu:"Street Food Fusion",tg:"internazionale",ws:"https://www.google.com/search?q=Mogo%20ristorante%20Milano",st:"Street food fusion con influenze asiatiche e latinoamericane. Veloce, economico.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:11,l:"11/20"},rv:["I bao sono morbidi e ben ripieni.","Qualita degli ingredienti sorprendentemente alta per street food.","Miglior rapporto qualita/prezzo di Porta Venezia."]},
  {n:"Murataya",a:"Via San Glicerio 2, Bicocca",pl:2,pr:"€€ · ~45€",cu:"Giapponese Tradizionale",tg:"giapponese",ws:"https://www.google.com/search?q=Murataya%20ristorante%20Milano",st:"Trattoria giapponese autentica a conduzione familiare dello chef Hitoshi Murata. Cucina casalinga nipponica, nessun sushi all-you-can-eat.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Cucina giapponese vera, non fusion: sapori autentici e materie prime eccellenti.","Lo chef Murata ti fa sentire ospite della sua casa di Tokyo.","La tempura soba e i piatti del giorno sono sempre una scoperta."]},
  {n:"Nobu Milano",a:"Via Gastone Pisoni 1, Duomo",pl:5,pr:"€€€€€ · ~150€",cu:"Giapponese Fusion",tg:"giapponese",ws:"https://www.google.com/search?q=Nobu%20Milano%20ristorante%20Milano",st:"L unica sede italiana della leggendaria catena di Nobu Matsuhisa, dentro l Armani Hotel. Cucina giapponese con influenze peruviane.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Il black cod miso e il piatto iconico: leggendario e irripetibile.","Ambiente fashion e internazionale al massimo.","Il lounge bar e uno dei posti piu glamour della citta."]},
  {n:"Nott",a:"Piazza del Duomo, Duomo",pl:3,pr:"€€€ · ~65€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://www.google.com/search?q=Nott%20ristorante%20Milano",st:"Ristorante contemporaneo nel cuore di Milano. Cucina italiana moderna con forte attenzione alla stagionalita.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Cucina pulita e precisa, ingredienti di stagione ben valorizzati.","Uno dei nuovi indirizzi piu interessanti del centro citta.","Un alternativa solida ai grandi stellati."]},
  {n:"Onest",a:"Via Savona 1, Tortona",pl:2,pr:"€€ · ~45€",cu:"Italiana Moderna",tg:"italiana",ws:"https://www.google.com/search?q=Onest%20ristorante%20Milano",st:"Ristorante contemporaneo nel distretto del design. Cucina di mercato e vini naturali.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Cucina onesta e ben eseguita, come suggerisce il nome.","La pasta del giorno e sempre una piacevole sorpresa.","Miglior rapporto qualita/prezzo nel distretto del design."]},
  {n:"Orizzonti",a:"Viale Monte Nero 56, Porta Romana",pl:3,pr:"€€€ · ~60€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://www.google.com/search?q=Orizzonti%20ristorante%20Milano",st:"Cucina italiana contemporanea con forte attenzione agli ingredienti di stagione.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Cucina pulita e precisa, ingredienti di stagione con rispetto.","Carta dei vini sorprendente: etichette ricercate a prezzi onesti.","I primi piatti sono il punto di forza: pasta fatta in casa."]},
  {n:"Osaka",a:"Via Valenza 18, Navigli",pl:2,pr:"€€ · ~40€",cu:"Giapponese",tg:"giapponese",ws:"https://www.google.com/search?q=Osaka%20ristorante%20Milano",st:"Storico ristorante giapponese dei Navigli. Cucina autentica e prezzi onesti.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Un classico dei Navigli che non tradisce mai. Cucina giapponese autentica.","Il ramen e il sushi sono preparati con cura e ingredienti freschi.","Ambiente informale e accogliente."]},
  {n:"Osteria Pugliese Gatto Bianco",a:"Via Jommelli 20, Lambrate",pl:2,pr:"€€ · ~38€",cu:"Pugliese",tg:"italiana",ws:"https://www.google.com/search?q=Osteria%20Pugliese%20Gatto%20Bianco%20ristorante%20Milano",st:"La Puglia autentica a Milano: orecchiette, burrata, fave e cicoria.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:12,l:"12/20"},rv:["Le orecchiette alle cime di rapa sono quelle vere.","La burrata fresca arriva direttamente dalla Puglia.","Il pane di Altamura come benvenuto e gia una dichiarazione d’intenti."]},
  {n:"Osteria San Giovanni",a:"Via S. Giovanni sul Muro 8, Cairoli",pl:2,pr:"€€ · ~40€",cu:"Lombarda",tg:"italiana",ws:"https://www.google.com/search?q=Osteria%20San%20Giovanni%20ristorante%20Milano",st:"Osteria autentica con cucina della tradizione lombarda. Bib Gourmand.",mi:{s:0,b:1,g:0},gr:{f:2,l:"Due Forchette"},es:{v:13,l:"13/20"},rv:["La cassoeula e leggendaria.","La cotoletta probabilmente la migliore della citta.","Da anni il mio posto preferito per una cena in compagnia."]},
  {n:"Paper Moon Giardino",a:"Via Bagutta 1, San Babila",pl:3,pr:"€€€ · ~75€",cu:"Italiana Classica",tg:"italiana",ws:"https://www.google.com/search?q=Paper%20Moon%20Giardino%20ristorante%20Milano",st:"Il giardino segreto di Milano. Cucina italiana classica in uno dei cortili piu belli.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Il giardino estivo e tra i luoghi piu belli di tutta Milano.","La cucina italiana classica e eseguita con grande cura.","Servizio impeccabile e discreto."]},
  {n:"Particolare",a:"Via Sottocorno 13, Porta Venezia",pl:3,pr:"€€€ · ~65€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://www.google.com/search?q=Particolare%20ristorante%20Milano",st:"Ristorante contemporaneo a Porta Venezia. Cucina italiana di qualita in ambiente elegante e raccolto.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Un posto davvero particolare: cucina curata e atmosfera intima.","I primi piatti sono il punto di forza, sempre eseguiti con precisione.","Servizio attento e discreto, perfetto per occasioni speciali."]},
  {n:"Pellico 3",a:"Via Silvio Pellico 3, Duomo",pl:4,pr:"€€€€ · ~100€",cu:"Fine Dining",tg:"italiana",ws:"https://www.google.com/search?q=Pellico%203%20ristorante%20Milano",st:"Fine dining nel centro storico. Eleganza sobria, cucina di alto livello. Una stella Michelin.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["Cucina d’autore senza eccessi, ogni piatto racconta una storia.","Servizio altissimo livello, attento senza essere invadente.","Ottimo per cene d’affari o occasioni speciali."]},
  {n:"Poporoya",a:"Via Bartolomeo Eustachi 17, Porta Venezia",pl:1,pr:"€ · ~20€",cu:"Giapponese Tradizionale",tg:"giapponese",ws:"https://www.google.com/search?q=Poporoya+ristorante+Milano",st:"Sushi bar storico dal 1980, il primo ristorante giapponese di Milano. Maestro Shiro Hirazawa porta la cucina tradizionale nipponica nella sua forma piu autentica: sushi, sashimi, ramen, udon, tempura. Un pellegrinaggio obbligatorio.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Il primo sushi bar di Milano: aperto negli anni 80 dal Maestro Shiro, icona della cucina giapponese in Italia.","Frequentato dalla comunita giapponese di Milano: la garanzia definitiva di autenticita.","Sushi, ramen, udon, tempura, takoyaki: la cucina giapponese tradizionale nella sua forma piu pura."]},
  {n:"Rame Bistrot",a:"Via Poerio 3, Porta Venezia",pl:2,pr:"€€ · ~42€",cu:"Italiana Moderna",tg:"italiana",ws:"https://www.google.com/search?q=Rame%20Bistrot%20ristorante%20Milano",st:"Bistrot contemporaneo a Porta Venezia. Cucina italiana moderna, ingredienti selezionati, atmosfera calda e informale.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Un bistrot solido e affidabile: cucina curata senza fronzoli.","I primi piatti fatti in casa sono il punto di forza del menu.","Servizio gentile e ambiente piacevole, perfetto per una cena di quartiere."]},
  {n:"Ratana",a:"Via G. De Castillia 28, Porta Garibaldi",pl:3,pr:"€€€ · ~60€",cu:"Milanese",tg:"italiana",ws:"https://www.google.com/search?q=Ratana%20ristorante%20Milano",st:"Cucina milanese contemporanea tra gli orti urbani di Porta Garibaldi. Una stella Michelin.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["Il risotto alla milanese e probabilmente il migliore di Milano.","La cotoletta e alta, dorata, burro perfetto.","Il giardino e uno dei piu belli della citta."]},
  {n:"Razdora",a:"Via Molino delle Armi 48, Duomo",pl:3,pr:"€€€ · ~65€",cu:"Emiliana",tg:"italiana",ws:"https://www.google.com/search?q=Razdora%20ristorante%20Milano",st:"La cucina emiliana nella sua forma piu raffinata. Tortellini in brodo, tagliatelle al ragu.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Il tortellino in brodo originale: piccolo, saporito, brodo profondo.","Le tagliatelle al ragu bolognese sono il piatto cult.","Il culatello e fuori categoria."]},
  {n:"Risus Risotteria",a:"Via Panfilo Castaldi 20, Porta Venezia",pl:2,pr:"€€ · ~30€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://www.google.com/search?q=Risus%20Risotteria%20ristorante%20Milano",st:"La risotteria contemporanea di Milano: menu completamente gluten free con risotti classici e gourmet.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:12,l:"12/20"},rv:["Il risotto milanese con ossobuco e eseguito con tecnica e cura.","Le Bombas de Riso sono il piatto da ordinare assolutamente.","Ottimo rapporto qualita/prezzo per la zona Buenos Aires."]},
  {n:"Roppongi",a:"Via Canova 33, Sarpi",pl:3,pr:"€€€ · ~70€",cu:"Sushi Omakase",tg:"giapponese",ws:"https://www.google.com/search?q=Roppongi%20ristorante%20Milano",st:"Omakase e sushi di qualita. Il pesce arriva dal Giappone. Una stella Michelin.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["L’omakase e un’esperienza da vivere almeno una volta.","Toro, uni e salmone selvatico di qualita che non si trova altrove.","Uno dei migliori sushi bar d’Italia."]},
  {n:"Sali",a:"Via B. Marcello 88, Citta Studi",pl:2,pr:"€€ · ~38€",cu:"Pesce",tg:"pesce",ws:"https://www.google.com/search?q=Sali%20ristorante%20Milano",st:"Piccolo indirizzo di cucina di mare informale. Menu breve, prodotto freschissimo.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:13,l:"13/20"},rv:["Miglior rapporto qualita/prezzo per il pesce a Milano.","La zuppa di pesce e memorabile: profumata, sostanziosa, generosa.","Un posto che fa della semplicita la propria forza."]},
  {n:"Sandi",a:"Via Lomellina 14, Porta Romana",pl:2,pr:"€€ · ~42€",cu:"Italiana Moderna",tg:"italiana",ws:"https://www.google.com/search?q=Sandi%20ristorante%20Milano",st:"Piccolo ristorante di quartiere con cucina sincera. Menu breve e rotazione stagionale.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Un posto che fa bene all’anima. Cucina vera, senza fronzoli.","La pasta fresca e motivo sufficiente per tornare ogni settimana.","Tra i migliori rapporti qualita/prezzo della zona."]},
  {n:"Sea Signora",a:"Via Fiori Chiari 32, Brera",pl:4,pr:"€€€€ · ~120€",cu:"Pesce",tg:"pesce",ws:"https://www.google.com/search?q=Sea%20Signora%20ristorante%20Milano",st:"Design anni 80, pavimenti in marmo, velluti porpora e acquario cilindrico. Cucina di mare cosmopolita.",mi:{s:0,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:16,l:"16/20"},rv:["Crudi di mare straordinari, materia prima di altissimo livello.","Cucina mediterranea con tocchi mediorientali. Servizio impeccabile.","La frittura di calamari di Mazara con labneh e fantastica."]},
  {n:"Seta",a:"Via Andegari 9, Duomo",pl:5,pr:"€€€€€ · ~200€",cu:"Alta Cucina",tg:"italiana",ws:"https://www.google.com/search?q=Seta%20ristorante%20Milano",st:"Due stelle Michelin al Mandarin Oriental. Chef Antonio Guida, cucina italiana nell’olimpo gastronomico.",mi:{s:2,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:19,l:"19/20"},rv:["Una delle esperienze gastronomiche piu complete d’Italia.","Menu degustazione straordinario: tecnica, creativita, tradizione.","Servizio di rara perfezione. Sommelier tra i migliori d’Italia."]},
  {n:"Sogni",a:"Via Orti 14, Porta Romana",pl:3,pr:"€€€ · ~60€",cu:"Italiana Creativa",tg:"italiana",ws:"https://www.google.com/search?q=Sogni%20ristorante%20Milano",st:"Piccolo ristorante con cucina italiana creativa. Chef giovane e ambizioso.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Una scoperta bellissima. La cucina e ambiziosa e centrata.","Menu degustazione: viaggio tra creativita e tradizione.","Pochi tavoli garantiscono attenzione personalizzata."]},
  {n:"Starita",a:"Via Procaccini 20, Sarpi",pl:1,pr:"€ · ~25€",cu:"Pizza Napoletana",tg:"pizza",ws:"https://www.google.com/search?q=Starita%20ristorante%20Milano",st:"La leggendaria pizzeria napoletana di Materdei a Milano. Lievito madre e forno a legna.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:13,l:"13/20"},rv:["La pizza napoletana piu autentica di Milano.","Friggitoria straordinaria: montanarine, cuoppo, crocchette.","Prezzi paragonabili a Napoli, qualita idem."]},
  {n:"Sumire",a:"Via Varese 1, Moscova",pl:2,pr:"€€ · ~38€",cu:"Giapponese Tradizionale",tg:"giapponese",ws:"https://www.google.com/search?q=Sumire+ristorante+Milano",st:"Piccola trattoria giapponese autentica in zona Moscova. Cucina che va molto oltre il sushi: takoyaki, okonomiyaki, kushikatsu, katsudon, curry giapponese, ramen. Frequentata dalla comunita giapponese. Prenotare.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Una delle rare trattorie giapponesi autentiche di Milano: la cucina va ben oltre il sushi.","Frequentata dalla comunita giapponese di Milano: garanzia di autenticita assoluta.","Takoyaki, okonomiyaki, curry e ramen come in Giappone: piccolo, intimo, sempre pieno."]},
  {n:"Sushi Matsu Omakase",a:"Via Napo Torriani 34, Repubblica",pl:4,pr:"€€€€ · ~120€",cu:"Sushi Omakase",tg:"giapponese",ws:"https://www.google.com/search?q=Sushi%20Matsu%20Omakase%20ristorante%20Milano",st:"Omakase puro. Il pesce arriva dal Giappone e il cuoco lavora davanti agli ospiti con precisione.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["L’omakase qui e un’esperienza autentica e commovente.","Il pesce importato dal Giappone e di una qualita rara in Italia.","Pochi posti al bancone, prenotazione con mesi di anticipo."]},
  {n:"Terrazza Triennale",a:"Viale Alemagna 6, Parco Sempione",pl:3,pr:"€€€ · ~65€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://www.google.com/search?q=Terrazza%20Triennale%20ristorante%20Milano",st:"Rooftop del Palazzo dell Arte con vista mozzafiato su Milano. Menu stagionale di Tommaso Arrigoni. Vista Castello e Madonnina.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["La vista sullo skyline di Milano dalla terrazza non ha rivali in citta.","Il menu Meneghinas con tapas lombarde e cocktail vintage e brillante.","D estate sotto il cielo con Castello e Duomo all orizzonte e magico."]},
  {n:"Terroir",a:"Via Meda 10, Porta Romana",pl:3,pr:"€€€ · ~60€",cu:"Vino Naturale",tg:"italiana",ws:"https://www.google.com/search?q=Terroir%20ristorante%20Milano",st:"Enoteca con cucina dedicata ai vini naturali. Carta dei vini straordinaria.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Selezione di vini naturali tra le migliori d’Italia.","La cucina e essenziale e corretta, pensata per valorizzare il vino.","Le degustazioni guidate sono eventi preziosi per gli appassionati."]},
  {n:"Trattoria da Panciroli",a:"Via Vigevano 6, Navigli",pl:2,pr:"€€ · ~35€",cu:"Italiana Tradizionale",tg:"italiana",ws:"https://www.google.com/search?q=Trattoria%20da%20Panciroli%20ristorante%20Milano",st:"Storica trattoria milanese ai Navigli. Cucina della tradizione genuina, ambiente informale, prezzi onesti.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:12,l:"12/20"},rv:["Una trattoria vera, senza fronzoli: cucina casalinga di grande qualita.","I Navigli che non ti aspetti: niente turisti, solo milanesi doc.","Il risotto e i secondi della tradizione sono il motivo per tornare."]},
  {n:"Trattoria del Nuovo Macello",a:"Via C. Lombroso 20, Porta Romana",pl:2,pr:"€€ · ~40€",cu:"Lombarda",tg:"italiana",ws:"https://www.google.com/search?q=Trattoria%20del%20Nuovo%20Macello%20ristorante%20Milano",st:"Una delle trattorie piu autentiche di Milano. Cucina lombarda vera. Bib Gourmand.",mi:{s:0,b:1,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["La trippa alla milanese e la migliore della citta.","Cassoeula d’inverno: scalda il corpo e l’anima.","Un’istituzione che non ha ceduto alle mode."]},
  {n:"Trattoria del Pescatore",a:"Via A. Vannucci 5, Porta Romana",pl:2,pr:"€€ · ~45€",cu:"Pesce Tradizionale",tg:"pesce",ws:"https://www.google.com/search?q=Trattoria%20del%20Pescatore%20ristorante%20Milano",st:"Trattoria di mare classica. Pesce sempre fresco, ricette della tradizione marinara.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:12,l:"12/20"},rv:["Una trattoria di mare come non se ne trovano facilmente.","La frittura mista e il benchmark: leggera, croccante.","Ci si sente ospiti di qualcuno, non clienti."]},
  {n:"Trattoria della Gloria",a:"Via Gustavo Fara 14, Repubblica",pl:2,pr:"€€ · ~38€",cu:"Italiana Tradizionale",tg:"italiana",ws:"https://www.google.com/search?q=Trattoria%20della%20Gloria%20ristorante%20Milano",st:"Trattoria classica milanese in zona Repubblica. Cucina della tradizione lombarda con materie prime selezionate.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["La cucina lombarda nella sua forma piu onesta e diretta.","Il cotechino con lenticchie e un piatto da non perdere.","Gestione familiare che mette a proprio agio dal primo momento."]},
  {n:"Trattoria Don Ciccio",a:"Via Losanna 11, Isola",pl:2,pr:"€€ · ~38€",cu:"Siciliana",tg:"italiana",ws:"https://www.google.com/search?q=Trattoria%20Don%20Ciccio%20ristorante%20Milano",st:"Vera cucina siciliana da quattro generazioni, originari di Bagheria. Trattoria autentica nel quartiere Isola.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:12,l:"12/20"},rv:["La pasta con le sarde e quella autentica: uvetta, pinoli, finocchietto.","La caponata fatta in casa e complessa e profumata come quella di Bagheria.","Una trattoria familiare che conserva una tradizione preziosa."]},
  {n:"Trattoria Masuelli San Marco",a:"Viale Umbria 80, Porta Romana",pl:2,pr:"€€ · ~45€",cu:"Lombarda",tg:"italiana",ws:"https://www.google.com/search?q=Trattoria%20Masuelli%20San%20Marco%20ristorante%20Milano",st:"Trattoria familiare dal 1921. Cucina milanese borghese alla quarta generazione. Bib Gourmand.",mi:{s:0,b:1,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["La luganega con pure e il comfort food nella sua forma piu alta.","Gestione familiare alla quarta generazione. Si sente l’orgoglio.","Un’istituzione che resiste al tempo e alle mode."]},
  {n:"Trattoria Rovello",a:"Via Tivoli 2, Cairoli",pl:2,pr:"€€ · ~40€",cu:"Milanese",tg:"italiana",ws:"https://www.google.com/search?q=Trattoria%20Rovello%20ristorante%20Milano",st:"Trattoria storica nel centro di Milano. Cucina della tradizione milanese.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Le mondeghili (polpette milanesi) sono quelle vere.","Il risotto al midollo qui lo fanno come una volta.","Una delle trattorie piu autentiche rimaste in centro."]},
  {n:"Trattoria Sole",a:"Via Carlo Valvassori Peroni 41, Citta Studi",pl:2,pr:"€€ · ~35€",cu:"Italiana Creativa",tg:"trattoria",ws:"https://www.google.com/search?q=Trattoria+Sole+Milano+Valvassori+Peroni",st:"Trattoria dall anima retra in zona Lambrate: sembra di entrare in casa di un amico, con mobili della nonna e tavoli tutti diversi tra loro. Cucina italiana creativa con radici nella tradizione: tagliolini neri con crema di acciughe, filetto di maiale con crosta di sesamo, cotolettine in carpione. Crostata fatta in casa. Rating 4.4 su oltre 1100 recensioni.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Sembra di entrare nell appartamento di un amico: arredamento vintage anni 50-60, mobili della nonna, atmosfera intima e calda.","Cucina italiana creativa con un tocco personale: tagliolini neri con crema di acciughe e pinoli, filetto con sesamo, dolci fatti in casa.","4.4 su oltre 1100 recensioni: uno dei locali piu amati di Lambrate, ottimo rapporto qualita-prezzo. Prenotare."]},
  {n:"Trippa",a:"Via Giorgio Vasari 1, Porta Romana",pl:3,pr:"€€€ · ~50€",cu:"Quinto Quarto",tg:"italiana",ws:"https://www.google.com/search?q=Trippa%20ristorante%20Milano",st:"Diego Rossi reinventa la cucina di recupero con tecnica e passione. Bib Gourmand Michelin.",mi:{s:0,b:1,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["La trippa fritta e un capolavoro: croccante fuori, morbida dentro.","Il vitello tonnato probabilmente il migliore di Milano.","Le tagliatelle al burro: la semplicita come perfezione."]},
  {n:"Tsukiji Market",a:"Via Mercalli 11, Porta Romana",pl:2,pr:"€€ · ~45€",cu:"Sushi",tg:"giapponese",ws:"https://www.google.com/search?q=Tsukiji%20Market%20ristorante%20Milano",st:"Ispirato al mercato del pesce di Tokyo: sushi e sashimi di qualita in ambiente informale.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Qualita del pesce eccezionale per prezzi cosi accessibili.","Sashimi misto: un inno alla freschezza. Tonno sempre perfetto.","Informale e vivace, senza la cerimonia dei giapponesi di lusso."]},
  {n:"Via Stampa",a:"Via Vincenzo Monti 30, Cadorna",pl:3,pr:"€€€ · ~70€",cu:"Italiana Fine Dining",tg:"italiana",ws:"https://www.google.com/search?q=Via%20Stampa%20ristorante%20Milano",st:"Ristorante raffinato a Cadorna. Cucina italiana con forte attenzione ai prodotti regionali.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Ristorante solido e affidabile. Cucina precisa, ingredienti eccellenti.","Cantina eccezionale con etichette rare e sommelier preparato.","Servizio professionale e discreto. Non delude mai."]},
  {n:"Voja",a:"Via Melzo 8, Porta Venezia",pl:2,pr:"€€ · ~40€",cu:"Enoteca con Cucina",tg:"italiana",ws:"https://www.google.com/search?q=Voja%20ristorante%20Milano",st:"Enoteca con cucina a Porta Venezia. Il vino e protagonista: naturali, biodinamici, rari.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Selezione di vini straordinaria: etichette naturali e biodinamiche.","Il crudo di pesce abbinato al vino giusto e un’esperienza completa.","Uno dei pochi posti dove si beve bene senza spendere una fortuna."]},
  {n:"Yajiri Maison by Yumi",a:"Via Gorani 3, Duomo",pl:3,pr:"€€€ · ~70€",cu:"Giapponese Contemporanea",tg:"giapponese",ws:"https://www.google.com/search?q=Yajiri%20Maison%20by%20Yumi%20ristorante%20Milano",st:"Ristorante giapponese nel cuore di Milano con approccio creativo e materie prime di eccellenza.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Una delle proposte giapponesi piu interessanti degli ultimi anni a Milano.","Equilibrio perfetto tra tradizione e tocchi contemporanei.","Ambiente raccolto e intimo, servizio attento e appassionato."]},
  {n:"Yapa",a:"Via Petrella 12, Porta Venezia",pl:2,pr:"€€ · ~40€",cu:"Peruviana",tg:"internazionale",ws:"https://www.google.com/search?q=Yapa%20ristorante%20Milano",st:"Cucina peruviana autentica in ambiente vivace. Ceviche, tiradito, lomo saltado.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Il ceviche e fresco e ben bilanciato. Autenticita garantita.","Il lomo saltado preparato con wok e fuoco vivo.","Cocktail a base di pisco originali e ben costruiti."]},
  {n:"Yazawa",a:"Via San Fermo 1, Brera",pl:5,pr:"€€€€€ · ~120€",cu:"Wagyu Yakiniku",tg:"giapponese",ws:"https://www.google.com/search?q=Yazawa+ristorante+Milano+wagyu",st:"L unico ristorante Yazawa in Europa. Wagyu Kuroge A5 importato direttamente dal Giappone cotto alla griglia al tavolo in stile Yakiniku. Chef Tsuyoshi Noikura seleziona i tagli migliori. L esperienza piu esclusiva della cucina giapponese a Milano.",mi:{s:0,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["Il solo ristorante Yazawa in Europa: il Wagyu Kuroge A5 piu pregiato del Giappone al tavolo.","La cottura Yakiniku sulla griglia integrata al tavolo e condotta dallo staff: un rituale assoluto.","L esperienza piu esclusiva della cucina giapponese a Milano: i tagli migliori del manzo del Gunma."]},
  {n:"Zelo",a:"Via Villoresi 16, Navigli",pl:3,pr:"€€€ · ~60€",cu:"Italiana Contemporanea",tg:"italiana",ws:"https://www.google.com/search?q=Zelo%20ristorante%20Milano",st:"Cucina italiana contemporanea sui Navigli. Ambiente curato, ingredienti di stagione, carta dei vini interessante.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Cucina precisa e ben centrata, con prodotti di qualita.","Ambiente piacevole, perfetto per una cena rilassata sui Navigli.","La carta dei vini offre etichette ricercate a prezzi onesti."]},
  {n:"Zero Milano",a:"Corso Magenta 87, Cadorna",pl:3,pr:"€€€ · ~55€",cu:"Giapponese",tg:"giapponese",ws:"https://www.google.com/search?q=Zero%20Milano%20ristorante%20Milano",st:"Dal 2006 nella guida Michelin. Chef Hide Shinohara: tradizione giapponese e creativita italiana in perfetto equilibrio.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["I carpacci 007 con salsa calda sono il piatto firma: straordinari.","Zero compromessi sulla qualita: materie prime eccezionali.","Tra i migliori sushi di Milano da anni."]},
  {n:"Zio Pesce",a:"Via Conchetta 8, Navigli",pl:2,pr:"€€ · ~45€",cu:"Crudo di Mare",tg:"pesce",ws:"https://www.google.com/search?q=Zio%20Pesce%20ristorante%20Milano",st:"Piccolo indirizzo ai Navigli dedicato al crudo. Pescato freschissimo.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:13,l:"13/20"},rv:["Il crudo di mare piu fresco di Milano. Ostriche, gamberi, scampi.","Il plateau di crudi e il miglior inizio di serata.","Quasi impossibile trovare posto senza prenotazione."]}
];
var favs=new Set(JSON.parse(localStorage.getItem('mifav25')||'[]'));
var wish=new Set(JSON.parse(localStorage.getItem('miwish25')||'[]'));
function saveFavs(){localStorage.setItem('mifav25',JSON.stringify(Array.from(favs)));}
function saveWish(){localStorage.setItem('miwish25',JSON.stringify(Array.from(wish)));}

window.toggleWish=function(i){
  var n=R[i].n;
  wish.has(n)?wish.delete(n):wish.add(n);
  saveWish();updateWishCount();render();
};

window.toggleFav=function(i){
  var n=R[i].n;
  favs.has(n)?favs.delete(n):favs.add(n);
  saveFavs();

updateFavCount();render();
};

var S={c:'all',p:'all',g:'all',z:'all',q:'',fav:false,wish:false};

var mainZones=['brera','navigli','duomo','porta venezia','porta romana','porta garibaldi','moscova','sarpi','tortona','isola'];

function getZone(a){return a.split(',').pop().trim().toLowerCase();}

function maps(a){return'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(a+', Milano');}

function miBadge(r){
  if(r.mi.s>=1)return'<span class="sg mi">'+'\u2B50'.repeat(r.mi.s)+' '+(r.mi.s===1?'Una Stella':r.mi.s+' Stelle')+' <span class="gn">Michelin</span></span>';
  if(r.mi.b)return'<span class="sg mi">\uD83D\uDE0A Bib Gourmand <span class="gn">Michelin</span></span>';
  if(r.mi.g)return'<span class="sg mi" style="background:#f0fff4;border-color:#a8d5b5;color:#276749">\uD83C\uDF3F Green Star <span class="gn">Michelin</span></span>';
  return'<span class="sg mi fd">\u2B50 \u2013 <span class="gn">Michelin</span></span>';
}

function makeCard(r,i){
  var isFav=favs.has(r.n);
  var isWish=wish.has(r.n);
  var ta='https://www.tripadvisor.it/Search?q='+encodeURIComponent(r.n+' Milano');
  var rvs='';
  for(var k=0;k<r.rv.length;k++)rvs+='<div class="rv"><span class="st">\u2605\u2605\u2605\u2605\u2605</span><span>'+r.rv[k]+'</span></div>';
  return '<div class="card">'
    +'<button class="favbtn'+(isFav?' on':'')+'" onclick="toggleFav('+i+')">'+( isFav?'\u2764\uFE0F':'\uD83E\uDD0D')+'</button>'
    +'<button class="wishbtn'+(isWish?' on':'')+'" onclick="toggleWish('+i+')">'+( isWish?'\u2705':'\u2714\uFE0F')+'</button>'
    +'<div class="cb">'
    +'<div class="ctag"><span class="ccu">'+r.cu.toUpperCase()+'</span><span class="cpr">'+r.pr+'</span></div>'
    +'<h2 class="cn"><a href="'+r.ws+'" target="_blank" style="color:inherit;text-decoration:none;">'+r.n+'</a></h2>'
    +'<div class="lks">'
    +'<a href="'+maps(r.a)+'" target="_blank">\uD83D\uDCCD '+r.a+'</a>'
    +'<a href="'+r.ws+'" target="_blank" class="ws">\uD83C\uDF10 Sito web</a>'
    +'<a href="'+ta+'" target="_blank" class="ta">\uD83C\uDF7D TripAdvisor</a>'
    +'</div>'
    +'<div class="sc">'+miBadge(r)
    +'<span class="sg gr">'+'\uD83C\uDF74'.repeat(r.gr.f)+' '+r.gr.l+' <span class="gn">Gambero Rosso</span></span>'
    +'<span class="sg es">\u2615 '+r.es.l+' <span class="gn">L\u2019Espresso</span></span>'
    +'</div>'
    +'<p class="cs">'+r.st+'</p>'
    +'<div class="rvs">'+rvs+'</div>'
    +'</div></div>';
}

function updateFavCount(){
  var n=favs.size;
  document.getElementById('favc').textContent=n>0?'('+n+')':'';
}
function updateWishCount(){
  var n=wish.size;
  document.getElementById('wishc').textContent=n>0?'('+n+')':'';
}

function render(){
  var f=[];
  for(var i=0;i<R.length;i++){
    var r=R[i];
    if(S.c!=='all'&&r.tg!==S.c)continue;
    if(S.p!=='all'&&r.pl!==parseInt(S.p))continue;
    if(S.g==='michelin'&&!r.mi.s&&!r.mi.b&&!r.mi.g)continue;
    if(S.g==='gambero'&&r.gr.f<2)continue;
    if(S.g==='espresso'&&r.es.v<15)continue;
    if(S.z!=='all'){var rz=getZone(r.a);if(S.z==='other'){if(mainZones.indexOf(rz)!==-1)continue;}else{if(rz!==S.z)continue;}}
    if(S.fav&&!favs.has(r.n))continue;
    if(S.wish&&!wish.has(r.n))continue;
    if(S.q){var q=S.q.toLowerCase();var ok=false;var ff=[r.n,r.cu,r.a,r.st];for(var j=0;j<ff.length;j++){if(ff[j].toLowerCase().indexOf(q)>=0){ok=true;break;}}if(!ok)continue;}
    f.push(i);
  }
  document.getElementById('tot').textContent=f.length;
  var rcEl=document.getElementById('rc');if(rcEl)rcEl.textContent=f.length+' risultati';
  var grid=document.getElementById('grid');
  var cards=grid.querySelectorAll('.card');
  for(var k=0;k<cards.length;k++)cards[k].remove();
  document.getElementById('nr').style.display=f.length?'none':'block';
  for(var m=0;m<f.length;m++)grid.insertAdjacentHTML('beforeend',makeCard(R[f[m]],f[m]));
}

document.getElementById('cg').addEventListener('click',function(e){var b=e.target.closest('.fb');if(!b)return;document.querySelectorAll('#cg .fb').forEach(function(x){x.classList.remove('on');});b.classList.add('on');S.c=b.dataset.c;render();});
document.getElementById('pg').addEventListener('click',function(e){var b=e.target.closest('.fb');if(!b)return;document.querySelectorAll('#pg .fb').forEach(function(x){x.classList.remove('on');});b.classList.add('on');S.p=b.dataset.p;render();});
document.getElementById('gg').addEventListener('click',function(e){var b=e.target.closest('.fb');if(!b)return;document.querySelectorAll('#gg .fb').forEach(function(x){x.classList.remove('on');});b.classList.add('on');S.g=b.dataset.g;render();});
document.getElementById('favf').addEventListener('click',function(){S.fav=!S.fav;S.wish=false;document.getElementById('wishf').classList.remove('on');this.classList.toggle('on',S.fav);render();});
document.getElementById('wishf').addEventListener('click',function(){S.wish=!S.wish;S.fav=false;document.getElementById('favf').classList.remove('on');this.classList.toggle('on',S.wish);render();});
document.getElementById('srch').addEventListener('input',function(e){S.q=e.target.value;render();});
document.getElementById('zg').addEventListener('click',function(e){var b=e.target.closest('.fb');if(!b)return;document.querySelectorAll('#zg .fb').forEach(function(x){x.classList.remove('on');});b.classList.add('on');S.z=b.dataset.z;render();});

updateFavCount();
updateWishCount();
render();
